// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CaosDripStatus.
const (
	CaosDripStatusBrewing    CaosDripStatus = "brewing"
	CaosDripStatusDone       CaosDripStatus = "done"
	CaosDripStatusQueued     CaosDripStatus = "queued"
	CaosDripStatusUnassigned CaosDripStatus = "unassigned"
)

// Defines values for CaosErrorResponseCode.
const (
	CaosErrorCodeInvalid CaosErrorResponseCode = "invalid"
)

// Defines values for CaosOpName.
const (
	CaosOpAssign    CaosOpName = "assign"
	CaosOpMerge     CaosOpName = "merge"
	CaosOpNext      CaosOpName = "next"
	CaosOpRebrew    CaosOpName = "rebrew"
	CaosOpSetLane   CaosOpName = "set_lane"
	CaosOpSwapLanes CaosOpName = "swap_lanes"
	CaosOpUnassign  CaosOpName = "unassign"
	CaosOpUndo      CaosOpName = "undo"
)

// Defines values for ColorScreen.
const (
	ColorScreenCashier ColorScreen = "cashier"
	ColorScreenMaster  ColorScreen = "master"
	ColorScreenServe   ColorScreen = "serve"
)

// Defines values for ColorTargetType.
const (
	ColorTargetTypeItem     ColorTargetType = "Item"
	ColorTargetTypeItemType ColorTargetType = "ItemType"
)

// Defines values for InventoryLevel.
const (
	InventoryLevelCritical  InventoryLevel = "critical"
	InventoryLevelOk        InventoryLevel = "ok"
	InventoryLevelUntracked InventoryLevel = "untracked"
	InventoryLevelWarning   InventoryLevel = "warning"
)

// Defines values for StockEventKind.
const (
	StockEventKindAdjust  StockEventKind = "adjust"
	StockEventKindCount   StockEventKind = "count"
	StockEventKindReceipt StockEventKind = "receipt"
)

// Defines values for StockResourceKind.
const (
	StockResourceKindBean StockResourceKind = "bean"
	StockResourceKindCup  StockResourceKind = "cup"
)

// CaosDrip 抽出カード。1 回のドリップ（最大 2 杯）が 1 枚。order_ids と cups は lines から求めたもの
type CaosDrip struct {
	CreatedAt  time.Time          `json:"created_at"`
	Cups       int                `json:"cups"`
	Dripper    *int               `json:"dripper"`
	FinishedAt *time.Time         `json:"finished_at"`
	Id         openapi_types.UUID `json:"id"`

	// Interrupted 入れ直しのために途中でやめた抽出
	Interrupted bool                 `json:"interrupted"`
	Lines       []CaosDripLine       `json:"lines"`
	OrderIds    []openapi_types.UUID `json:"order_ids"`

	// QueuePos 待機列の並び順（ふだんは注文番号）
	QueuePos float64 `json:"queue_pos"`

	// RebrewOf 入れ直しのカードなら、元のカード
	RebrewOf  *openapi_types.UUID `json:"rebrew_of"`
	StartedAt *time.Time          `json:"started_at"`

	// Status unassigned＝未割当 / queued＝担当の待機列 / brewing＝抽出中（1 人 1 枚） / done＝抽出終了
	Status CaosDripStatus `json:"status"`

	// UpdatedAt 「1つ戻す」は、この値が操作の記録と同じとき（ほかの端末が触っていないとき）だけ戻す
	UpdatedAt time.Time `json:"updated_at"`
}

// CaosDripLine 抽出カードの中身の 1 行。注文番号や商品名は持たない（/api/ws/orders の注文から引く）
type CaosDripLine struct {
	Cups   int                `json:"cups"`
	ItemId openapi_types.UUID `json:"item_id"`

	// Nominee POS の指名（明細の assignee の前後の空白を落としたもの）。同じ商品でも指名ごとにカードを分ける
	Nominee *string            `json:"nominee"`
	OrderId openapi_types.UUID `json:"order_id"`
}

// CaosDripStatus unassigned＝未割当 / queued＝担当の待機列 / brewing＝抽出中（1 人 1 枚） / done＝抽出終了
type CaosDripStatus string

// CaosErrorResponse defines model for CaosErrorResponse.
type CaosErrorResponse struct {
	Code  *CaosErrorResponseCode `json:"code,omitempty"`
	Error string                 `json:"error"`
}

// CaosErrorResponseCode defines model for CaosErrorResponse.Code.
type CaosErrorResponseCode string

// CaosLane 列（ドリッパー 1〜6）の担当者。営業日ごとに持ち、配信では 1〜6 の 6 列が必ずそろう。担当者がいない列は name が空。
// senior は交代したときに画面が sohosai-shift の名簿（seniors）で判定したもの（名簿を読めない端末でも同じ表示になるように持つ）。
type CaosLane struct {
	Dripper int `json:"dripper"`

	// Name 担当者の名前（前後の空白を落としたもの）。空なら担当者なし
	Name string `json:"name"`

	// Senior 上級生（限定を淹れられる）か。担当者がいない列は false
	Senior bool `json:"senior"`

	// UpdatedAt 最後に替えた時刻。一度も替えていない列は null（「1つ戻す」は、この値が操作の記録と同じときだけ戻す）
	UpdatedAt *time.Time `json:"updated_at"`
}

// CaosOp name ごとに使うフィールド：
// assign（drip_id・dripper）/ unassign（drip_id）/ next（dripper。drip_id は任意で、終わらせるカード。今抽出中のカードと違えば 422）/ merge（first_id・second_id）/
// rebrew（source_id・cups・interrupt・dripper（null なら未割当）・queue_pos（null なら元の位置））/
// set_lane（dripper・person（空なら担当者なし）・senior）/ swap_lanes（dripper・other_dripper）/
// undo（op_id）
type CaosOp struct {
	// Cups 入れ直す杯数（元のカードの杯数まで）
	Cups    *int                `json:"cups,omitempty"`
	DripId  *openapi_types.UUID `json:"drip_id,omitempty"`
	Dripper *int                `json:"dripper"`
	FirstId *openapi_types.UUID `json:"first_id,omitempty"`

	// Interrupt 抽出中の元のカードを途中でやめる
	Interrupt *bool      `json:"interrupt,omitempty"`
	Name      CaosOpName `json:"name"`

	// OpId undo で戻す操作（操作の結果の op_id）
	OpId *openapi_types.UUID `json:"op_id,omitempty"`

	// OtherDripper swap_lanes で dripper の列と担当者を入れ替える列
	OtherDripper *int `json:"other_dripper,omitempty"`

	// Person set_lane の担当者の名前（前後の空白は落とす）。空なら担当者なし
	Person   *string             `json:"person,omitempty"`
	QueuePos *float64            `json:"queue_pos"`
	SecondId *openapi_types.UUID `json:"second_id,omitempty"`

	// Senior set_lane の担当者が上級生（限定を淹れられる）か。画面が sohosai-shift の名簿で判定して送る
	Senior   *bool               `json:"senior,omitempty"`
	SourceId *openapi_types.UUID `json:"source_id,omitempty"`
}

// CaosOpName defines model for CaosOp.Name.
type CaosOpName string

// CaosOpResult defines model for CaosOpResult.
type CaosOpResult struct {
	Changed []CaosDrip           `json:"changed"`
	Deleted []openapi_types.UUID `json:"deleted"`

	// Lanes この操作で担当者が変わった列（undo では、戻した列）
	Lanes []CaosLane `json:"lanes"`

	// OpId この操作の記録の ID。「1つ戻す」（undo）で指定する。undo の結果では空
	OpId string `json:"op_id"`

	// Readied この操作で準備完了にした注文（undo では、準備完了を外した注文）
	Readied []openapi_types.UUID `json:"readied"`
}

// CaosPracticeAdvanceRequest defines model for CaosPracticeAdvanceRequest.
type CaosPracticeAdvanceRequest struct {
	// At 練習の時刻
	At time.Time `json:"at"`
}

// CaosPracticeCreateRequest defines model for CaosPracticeCreateRequest.
type CaosPracticeCreateRequest struct {
	// EndsAt 練習の時間帯の終わり（始まりから 6 時間まで）。時計はこのあと 3 時間まで進められる（残ったカードを淹れ終えるため）
	EndsAt time.Time `json:"ends_at"`

	// Lanes 列の担当者の初めの状態（任意）。練習の中で交代しても本番の列には響かない
	Lanes  *[]CaosPracticeLaneInput `json:"lanes,omitempty"`
	Orders []CaosPracticeOrderInput `json:"orders"`

	// StartsAt 練習の時間帯の始まり（過去の時刻）。練習の時計はここから始まる
	StartsAt time.Time `json:"starts_at"`
}

// CaosPracticeItem 練習の盤面の商品。カードの明細の item_id はこの id
type CaosPracticeItem struct {
	Id   openapi_types.UUID `json:"id"`
	Key  string             `json:"key"`
	Name string             `json:"name"`
	Type string             `json:"type"`
}

// CaosPracticeLaneInput defines model for CaosPracticeLaneInput.
type CaosPracticeLaneInput struct {
	Dripper int    `json:"dripper"`
	Name    string `json:"name"`
	Senior  bool   `json:"senior"`
}

// CaosPracticeLineInput 練習に送る注文の明細の 1 行（同じ商品が何杯か）
type CaosPracticeLineInput struct {
	// ItemKey 商品を見分けるキー（実績データの商品の ID。空なら名前）。同じキーは同じ商品（統合できるのは同じ商品どうし）
	ItemKey  *string `json:"item_key,omitempty"`
	Name     string  `json:"name"`
	Price    int     `json:"price"`
	Quantity int     `json:"quantity"`

	// Type 商品の種類（POS の item_type の name と同じ。hot・ice・iceOre・milk・others・limited など）。milk と others は抽出しない
	Type string `json:"type"`
}

// CaosPracticeOpRequest defines model for CaosPracticeOpRequest.
type CaosPracticeOpRequest struct {
	// At 練習の時刻（操作の前に、ここまで時計を進める）
	At time.Time `json:"at"`

	// Op name ごとに使うフィールド：
	// assign（drip_id・dripper）/ unassign（drip_id）/ next（dripper。drip_id は任意で、終わらせるカード。今抽出中のカードと違えば 422）/ merge（first_id・second_id）/
	// rebrew（source_id・cups・interrupt・dripper（null なら未割当）・queue_pos（null なら元の位置））/
	// set_lane（dripper・person（空なら担当者なし）・senior）/ swap_lanes（dripper・other_dripper）/
	// undo（op_id）
	Op CaosOp `json:"op"`
}

// CaosPracticeOpResult defines model for CaosPracticeOpResult.
type CaosPracticeOpResult struct {
	// OpId この操作の記録の ID。「1つ戻す」（undo）で指定する。undo の結果では空
	OpId string `json:"op_id"`

	// State 練習用の盤面。カードと列の担当者は本番と同じ形（CaosDrip・CaosLane）
	State CaosPracticeState `json:"state"`
}

// CaosPracticeOrder defines model for CaosPracticeOrder.
type CaosPracticeOrder struct {
	BillingAmount int                     `json:"billing_amount"`
	CreatedAt     time.Time               `json:"created_at"`
	Id            openapi_types.UUID      `json:"id"`
	Lines         []CaosPracticeOrderLine `json:"lines"`
	OrderNo       int                     `json:"order_no"`

	// ReadyAt 練習の中で準備完了になった時刻（練習の時計）。まだなら null
	ReadyAt *time.Time `json:"ready_at"`
}

// CaosPracticeOrderInput defines model for CaosPracticeOrderInput.
type CaosPracticeOrderInput struct {
	BillingAmount int `json:"billing_amount"`

	// CreatedAt 注文の時刻（練習の時間帯の中）
	CreatedAt time.Time               `json:"created_at"`
	Lines     []CaosPracticeLineInput `json:"lines"`
	OrderNo   int                     `json:"order_no"`
}

// CaosPracticeOrderLine defines model for CaosPracticeOrderLine.
type CaosPracticeOrderLine struct {
	ItemId   openapi_types.UUID `json:"item_id"`
	Price    int                `json:"price"`
	Quantity int                `json:"quantity"`
}

// CaosPracticeState 練習用の盤面。カードと列の担当者は本番と同じ形（CaosDrip・CaosLane）
type CaosPracticeState struct {
	Drips  []CaosDrip         `json:"drips"`
	EndsAt time.Time          `json:"ends_at"`
	Id     openapi_types.UUID `json:"id"`
	Items  []CaosPracticeItem `json:"items"`
	Lanes  []CaosLane         `json:"lanes"`

	// NextArrivalAt 次に届く注文の時刻。もう無ければ null
	NextArrivalAt *time.Time `json:"next_arrival_at"`

	// Now 練習の時計（最後に画面から受け取った時刻）
	Now time.Time `json:"now"`

	// Orders もう届いた注文（作った順）
	Orders   []CaosPracticeOrder `json:"orders"`
	StartsAt time.Time           `json:"starts_at"`

	// TotalOrders 練習の注文の全部の数
	TotalOrders int `json:"total_orders"`

	// Version 盤面が変わるたびに 1 つ増える（画面が古い応答で上書きしないため）
	Version int `json:"version"`
}

// CashierStateResponse defines model for CashierStateResponse.
type CashierStateResponse struct {
	// EdittingOrder レジで編集中の注文。フロントの orderSchema の JSON をそのまま保持し、サーバーは上の階層のキーと型を確かめる以外は中身を解釈しない
	EdittingOrder map[string]interface{} `json:"editting_order"`

	// SubmittedOrderId 直前に確定した注文の ID。編集中は null
	SubmittedOrderId *openapi_types.UUID `json:"submitted_order_id"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

// CashierStateUpdateRequest defines model for CashierStateUpdateRequest.
type CashierStateUpdateRequest struct {
	EdittingOrder    map[string]interface{} `json:"editting_order"`
	SubmittedOrderId *openapi_types.UUID    `json:"submitted_order_id"`
}

// ColorScreen 背景色を適用する画面
type ColorScreen string

// ColorSettingResponse defines model for ColorSettingResponse.
type ColorSettingResponse struct {
	Color string             `json:"color"`
	Id    openapi_types.UUID `json:"id"`

	// Screen 背景色を適用する画面
	Screen ColorScreen `json:"screen"`

	// TargetId Item または ItemType の ID
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType 背景色を設定する対象の種類
	TargetType ColorTargetType `json:"target_type"`
}

// ColorSettingUpsertRequest defines model for ColorSettingUpsertRequest.
type ColorSettingUpsertRequest struct {
	Color string `json:"color"`

	// Screen 背景色を適用する画面
	Screen ColorScreen `json:"screen"`

	// TargetId Item または ItemType の ID
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType 背景色を設定する対象の種類
	TargetType ColorTargetType `json:"target_type"`
}

// ColorTargetType 背景色を設定する対象の種類
type ColorTargetType string

// CommentCreateRequest defines model for CommentCreateRequest.
type CommentCreateRequest struct {
	Author string `json:"author"`
	Text   string `json:"text"`
}

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	Author    string             `json:"author"`
	CreatedAt time.Time          `json:"created_at"`
	OrderId   openapi_types.UUID `json:"order_id"`
	Text      string             `json:"text"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// InventoryLevel untracked は棚卸し・入荷がまだ一度も無い
type InventoryLevel string

// InventoryRemindResponse defines model for InventoryRemindResponse.
type InventoryRemindResponse struct {
	Reason *string `json:"reason,omitempty"`
	Sent   bool    `json:"sent"`
}

// InventoryStatus defines model for InventoryStatus.
type InventoryStatus struct {
	// Consumed counted_at 以降の注文での消費量
	Consumed float64 `json:"consumed"`

	// CountedAt 最後の棚卸し。無ければ最初の入荷
	CountedAt       *time.Time `json:"counted_at"`
	CountedQuantity *float64   `json:"counted_quantity"`

	// Level untracked は棚卸し・入荷がまだ一度も無い
	Level InventoryLevel `json:"level"`

	// Received counted_at 以降の入荷・調整の合計
	Received          float64               `json:"received"`
	Remaining         *float64              `json:"remaining"`
	RemainingServings *float64              `json:"remaining_servings"`
	Resource          StockResourceResponse `json:"resource"`

	// Servings counted_at 以降に売れた杯数
	Servings int `json:"servings"`

	// ServingsLastHour 直近1時間に売れた杯数
	ServingsLastHour int `json:"servings_last_hour"`
}

// ItemCreateRequest defines model for ItemCreateRequest.
type ItemCreateRequest struct {
	Abbr       string             `json:"abbr"`
	ItemTypeId openapi_types.UUID `json:"item_type_id"`
	Name       string             `json:"name"`
}

// ItemResponse defines model for ItemResponse.
type ItemResponse struct {
	Abbr     string             `json:"abbr"`
	Id       openapi_types.UUID `json:"id"`
	ItemType ItemTypeResponse   `json:"item_type"`
	Name     string             `json:"name"`
}

// ItemTypeCreateRequest defines model for ItemTypeCreateRequest.
type ItemTypeCreateRequest struct {
	DisplayName string `json:"display_name"`
	Name        string `json:"name"`
}

// ItemTypeResponse defines model for ItemTypeResponse.
type ItemTypeResponse struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// ItemTypeUpdateRequest defines model for ItemTypeUpdateRequest.
type ItemTypeUpdateRequest struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// ItemUpdateRequest defines model for ItemUpdateRequest.
type ItemUpdateRequest struct {
	Abbr       string             `json:"abbr"`
	Id         openapi_types.UUID `json:"id"`
	ItemTypeId openapi_types.UUID `json:"item_type_id"`
	Name       string             `json:"name"`
}

// MasterStateResponse defines model for MasterStateResponse.
type MasterStateResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Type      string    `json:"type"`
}

// MasterStateUpdateRequest defines model for MasterStateUpdateRequest.
type MasterStateUpdateRequest struct {
	Type string `json:"type"`
}

// MenuCreateRequest defines model for MenuCreateRequest.
type MenuCreateRequest struct {
	Abbr  string            `json:"abbr"`
	Items []MenuItemRequest `json:"items"`
	Key   string            `json:"key"`
	Name  string            `json:"name"`
	Price int               `json:"price"`
}

// MenuInfo defines model for MenuInfo.
type MenuInfo struct {
	Assignee *string `json:"assignee"`

	// Id 注文明細ID
	Id   openapi_types.UUID `json:"id"`
	Menu MenuResponse       `json:"menu"`

	// MenuName 注文時点のメニュー名
	MenuName string `json:"menu_name"`

	// UnitPrice 注文時点のメニュー価格
	UnitPrice int `json:"unit_price"`
}

// MenuInfoCreate defines model for MenuInfoCreate.
type MenuInfoCreate struct {
	Assignee *string            `json:"assignee"`
	MenuId   openapi_types.UUID `json:"menu_id"`

	// OrderMenuId 更新時に残す既存明細のID。新規明細では省略する。価格・名称はサーバーが保存する。
	OrderMenuId *openapi_types.UUID `json:"order_menu_id,omitempty"`
}

// MenuItemRequest defines model for MenuItemRequest.
type MenuItemRequest struct {
	ItemId   openapi_types.UUID `json:"item_id"`
	Quantity int                `json:"quantity"`
}

// MenuItemResponse defines model for MenuItemResponse.
type MenuItemResponse struct {
	Item     ItemResponse `json:"item"`
	Quantity int          `json:"quantity"`
}

// MenuResponse defines model for MenuResponse.
type MenuResponse struct {
	Abbr  string             `json:"abbr"`
	Id    openapi_types.UUID `json:"id"`
	Items []MenuItemResponse `json:"items"`
	Key   string             `json:"key"`
	Name  string             `json:"name"`
	Price int                `json:"price"`
}

// MenuUpdateRequest defines model for MenuUpdateRequest.
type MenuUpdateRequest struct {
	Abbr  string             `json:"abbr"`
	Id    openapi_types.UUID `json:"id"`
	Items []MenuItemRequest  `json:"items"`
	Key   string             `json:"key"`
	Name  string             `json:"name"`
	Price int                `json:"price"`
}

// OrderCreateRequest defines model for OrderCreateRequest.
type OrderCreateRequest struct {
	BillingAmount     int                     `json:"billing_amount"`
	Comments          *[]CommentCreateRequest `json:"comments,omitempty"`
	DiscountOrderCups *int                    `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int                    `json:"discount_order_id"`
	MenuIds           []MenuInfoCreate        `json:"menu_ids"`
	OrderId           int                     `json:"order_id"`
	Received          int                     `json:"received"`
}

// OrderCupResponse defines model for OrderCupResponse.
type OrderCupResponse struct {
	Id   openapi_types.UUID `json:"id"`
	Item ItemResponse       `json:"item"`

	// OrderMenuId このカップを含む注文明細のID（MenuInfo.id）
	OrderMenuId openapi_types.UUID `json:"order_menu_id"`

	// ReadyAt このカップが準備完了になった時刻。未準備なら null
	ReadyAt *time.Time `json:"ready_at"`

	// ServedAt このカップを提供した時刻。未提供なら null
	ServedAt *time.Time `json:"served_at"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	BillingAmount int                `json:"billing_amount"`
	Comments      *[]CommentResponse `json:"comments,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`

	// Cups 注文のカップ（1杯ずつ）。注文した順に並ぶ。グッズだけの注文では空
	Cups              []OrderCupResponse `json:"cups"`
	DiscountOrderCups *int               `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int               `json:"discount_order_id"`
	Id                openapi_types.UUID `json:"id"`
	Menus             []MenuInfo         `json:"menus"`
	OrderId           int                `json:"order_id"`
	ReadyAt           *time.Time         `json:"ready_at"`
	Received          int                `json:"received"`
	ServedAt          *time.Time         `json:"served_at"`
}

// OrderUpdateRequest defines model for OrderUpdateRequest.
type OrderUpdateRequest struct {
	BillingAmount     int                `json:"billing_amount"`
	DiscountOrderCups *int               `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int               `json:"discount_order_id"`
	Id                openapi_types.UUID `json:"id"`
	MenuIds           []MenuInfoCreate   `json:"menu_ids"`
	OrderId           int                `json:"order_id"`
	ReadyAt           *time.Time         `json:"ready_at"`
	Received          int                `json:"received"`
	ServedAt          *time.Time         `json:"served_at"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Database  string    `json:"database"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// StockEventCreateRequest defines model for StockEventCreateRequest.
type StockEventCreateRequest struct {
	Kind     StockEventKind `json:"kind"`
	Note     *string        `json:"note,omitempty"`
	Quantity float64        `json:"quantity"`
}

// StockEventCreateResponse defines model for StockEventCreateResponse.
type StockEventCreateResponse struct {
	// ActualPerServing 前回の棚卸しから今回までの実測の1杯あたり使用量（count のときだけ）
	ActualPerServing *float64 `json:"actual_per_serving"`

	// Estimated 記録する直前の推定残量（count のときの答え合わせ用）
	Estimated *float64           `json:"estimated"`
	Event     StockEventResponse `json:"event"`
}

// StockEventKind defines model for StockEventKind.
type StockEventKind string

// StockEventResponse defines model for StockEventResponse.
type StockEventResponse struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Kind       StockEventKind     `json:"kind"`
	Note       *string            `json:"note,omitempty"`
	Quantity   float64            `json:"quantity"`
	ResourceId openapi_types.UUID `json:"resource_id"`
}

// StockResourceKind defines model for StockResourceKind.
type StockResourceKind string

// StockResourceRequest defines model for StockResourceRequest.
type StockResourceRequest struct {
	// Buffer 最低限残したい杯数。これを切ると危険扱い
	Buffer int               `json:"buffer"`
	Kind   StockResourceKind `json:"kind"`
	Name   string            `json:"name"`

	// NotifyFrom 残りがこの杯数を切ったら通知を始める
	NotifyFrom int `json:"notify_from"`

	// NotifyStep notify_from から何杯減るごとに通知するか
	NotifyStep int `json:"notify_step"`

	// PerServing 1杯あたりの量。残量を杯数に換算するのに使う（カップ 1、豆 15）
	PerServing float64 `json:"per_serving"`

	// Unit 数える単位（個 / g）
	Unit string `json:"unit"`
}

// StockResourceResponse defines model for StockResourceResponse.
type StockResourceResponse struct {
	// Buffer 最低限残したい杯数。これを切ると危険扱い
	Buffer int                `json:"buffer"`
	Id     openapi_types.UUID `json:"id"`
	Kind   StockResourceKind  `json:"kind"`
	Name   string             `json:"name"`

	// NotifyFrom 残りがこの杯数を切ったら通知を始める
	NotifyFrom int `json:"notify_from"`

	// NotifyStep notify_from から何杯減るごとに通知するか
	NotifyStep int `json:"notify_step"`

	// PerServing 1杯あたりの量。残量を杯数に換算するのに使う（カップ 1、豆 15）
	PerServing float64 `json:"per_serving"`

	// Unit 数える単位（個 / g）
	Unit string `json:"unit"`
}

// StockUsage defines model for StockUsage.
type StockUsage struct {
	// Amount アイテム1杯で使う量（カップ 1、豆 15 など）
	Amount     float64            `json:"amount"`
	ItemId     openapi_types.UUID `json:"item_id"`
	ResourceId openapi_types.UUID `json:"resource_id"`
}

// ReplaceStockUsagesJSONBody defines parameters for ReplaceStockUsages.
type ReplaceStockUsagesJSONBody = []StockUsage

// ApplyCaosOpJSONRequestBody defines body for ApplyCaosOp for application/json ContentType.
type ApplyCaosOpJSONRequestBody = CaosOp

// CreateCaosPracticeJSONRequestBody defines body for CreateCaosPractice for application/json ContentType.
type CreateCaosPracticeJSONRequestBody = CaosPracticeCreateRequest

// AdvanceCaosPracticeJSONRequestBody defines body for AdvanceCaosPractice for application/json ContentType.
type AdvanceCaosPracticeJSONRequestBody = CaosPracticeAdvanceRequest

// ApplyCaosPracticeOpJSONRequestBody defines body for ApplyCaosPracticeOp for application/json ContentType.
type ApplyCaosPracticeOpJSONRequestBody = CaosPracticeOpRequest

// UpdateCashierStateJSONRequestBody defines body for UpdateCashierState for application/json ContentType.
type UpdateCashierStateJSONRequestBody = CashierStateUpdateRequest

// UpsertColorSettingJSONRequestBody defines body for UpsertColorSetting for application/json ContentType.
type UpsertColorSettingJSONRequestBody = ColorSettingUpsertRequest

// CreateStockResourceJSONRequestBody defines body for CreateStockResource for application/json ContentType.
type CreateStockResourceJSONRequestBody = StockResourceRequest

// UpdateStockResourceJSONRequestBody defines body for UpdateStockResource for application/json ContentType.
type UpdateStockResourceJSONRequestBody = StockResourceRequest

// CreateStockEventJSONRequestBody defines body for CreateStockEvent for application/json ContentType.
type CreateStockEventJSONRequestBody = StockEventCreateRequest

// ReplaceStockUsagesJSONRequestBody defines body for ReplaceStockUsages for application/json ContentType.
type ReplaceStockUsagesJSONRequestBody = ReplaceStockUsagesJSONBody

// CreateItemTypeJSONRequestBody defines body for CreateItemType for application/json ContentType.
type CreateItemTypeJSONRequestBody = ItemTypeCreateRequest

// UpdateItemTypeJSONRequestBody defines body for UpdateItemType for application/json ContentType.
type UpdateItemTypeJSONRequestBody = ItemTypeUpdateRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = ItemCreateRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = ItemUpdateRequest

// UpdateMasterStateJSONRequestBody defines body for UpdateMasterState for application/json ContentType.
type UpdateMasterStateJSONRequestBody = MasterStateUpdateRequest

// CreateMenuJSONRequestBody defines body for CreateMenu for application/json ContentType.
type CreateMenuJSONRequestBody = MenuCreateRequest

// UpdateMenuJSONRequestBody defines body for UpdateMenu for application/json ContentType.
type UpdateMenuJSONRequestBody = MenuUpdateRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderCreateRequest

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody = OrderUpdateRequest

// CreateOrderCommentJSONRequestBody defines body for CreateOrderComment for application/json ContentType.
type CreateOrderCommentJSONRequestBody = CommentCreateRequest
