// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ColorScreen.
const (
	ColorScreenMaster ColorScreen = "master"
	ColorScreenServe  ColorScreen = "serve"
)

// Defines values for ColorTargetType.
const (
	ColorTargetTypeItem     ColorTargetType = "Item"
	ColorTargetTypeItemType ColorTargetType = "ItemType"
)

// ColorScreen 背景色を適用する画面
type ColorScreen string

// ColorSettingResponse defines model for ColorSettingResponse.
type ColorSettingResponse struct {
	Color string             `json:"color"`
	Id    openapi_types.UUID `json:"id"`

	// Screen 背景色を適用する画面
	Screen ColorScreen `json:"screen"`

	// TargetId Item または ItemType の ID
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType 背景色を設定する対象の種類
	TargetType ColorTargetType `json:"target_type"`
}

// ColorSettingUpsertRequest defines model for ColorSettingUpsertRequest.
type ColorSettingUpsertRequest struct {
	Color string `json:"color"`

	// Screen 背景色を適用する画面
	Screen ColorScreen `json:"screen"`

	// TargetId Item または ItemType の ID
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType 背景色を設定する対象の種類
	TargetType ColorTargetType `json:"target_type"`
}

// ColorTargetType 背景色を設定する対象の種類
type ColorTargetType string

// CommentCreateRequest defines model for CommentCreateRequest.
type CommentCreateRequest struct {
	Author string `json:"author"`
	Text   string `json:"text"`
}

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	Author    string             `json:"author"`
	CreatedAt time.Time          `json:"created_at"`
	OrderId   openapi_types.UUID `json:"order_id"`
	Text      string             `json:"text"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ItemCreateRequest defines model for ItemCreateRequest.
type ItemCreateRequest struct {
	Abbr       string             `json:"abbr"`
	ItemTypeId openapi_types.UUID `json:"item_type_id"`
	Name       string             `json:"name"`
}

// ItemResponse defines model for ItemResponse.
type ItemResponse struct {
	Abbr     string             `json:"abbr"`
	Id       openapi_types.UUID `json:"id"`
	ItemType ItemTypeResponse   `json:"item_type"`
	Name     string             `json:"name"`
}

// ItemTypeCreateRequest defines model for ItemTypeCreateRequest.
type ItemTypeCreateRequest struct {
	DisplayName string `json:"display_name"`
	Name        string `json:"name"`
}

// ItemTypeResponse defines model for ItemTypeResponse.
type ItemTypeResponse struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// ItemTypeUpdateRequest defines model for ItemTypeUpdateRequest.
type ItemTypeUpdateRequest struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// ItemUpdateRequest defines model for ItemUpdateRequest.
type ItemUpdateRequest struct {
	Abbr       string             `json:"abbr"`
	Id         openapi_types.UUID `json:"id"`
	ItemTypeId openapi_types.UUID `json:"item_type_id"`
	Name       string             `json:"name"`
}

// MasterStateResponse defines model for MasterStateResponse.
type MasterStateResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Type      string    `json:"type"`
}

// MasterStateUpdateRequest defines model for MasterStateUpdateRequest.
type MasterStateUpdateRequest struct {
	Type string `json:"type"`
}

// MenuCreateRequest defines model for MenuCreateRequest.
type MenuCreateRequest struct {
	Abbr  string            `json:"abbr"`
	Items []MenuItemRequest `json:"items"`
	Key   string            `json:"key"`
	Name  string            `json:"name"`
	Price int               `json:"price"`
}

// MenuInfo defines model for MenuInfo.
type MenuInfo struct {
	Assignee *string `json:"assignee"`

	// Id 注文明細ID
	Id   openapi_types.UUID `json:"id"`
	Menu MenuResponse       `json:"menu"`

	// MenuName 注文時点のメニュー名
	MenuName string `json:"menu_name"`

	// UnitPrice 注文時点のメニュー価格
	UnitPrice int `json:"unit_price"`
}

// MenuInfoCreate defines model for MenuInfoCreate.
type MenuInfoCreate struct {
	Assignee *string            `json:"assignee"`
	MenuId   openapi_types.UUID `json:"menu_id"`

	// OrderMenuId 更新時に残す既存明細のID。新規明細では省略する。価格・名称はサーバーが保存する。
	OrderMenuId *openapi_types.UUID `json:"order_menu_id,omitempty"`
}

// MenuItemRequest defines model for MenuItemRequest.
type MenuItemRequest struct {
	ItemId   openapi_types.UUID `json:"item_id"`
	Quantity int                `json:"quantity"`
}

// MenuItemResponse defines model for MenuItemResponse.
type MenuItemResponse struct {
	Item     ItemResponse `json:"item"`
	Quantity int          `json:"quantity"`
}

// MenuResponse defines model for MenuResponse.
type MenuResponse struct {
	Abbr  string             `json:"abbr"`
	Id    openapi_types.UUID `json:"id"`
	Items []MenuItemResponse `json:"items"`
	Key   string             `json:"key"`
	Name  string             `json:"name"`
	Price int                `json:"price"`
}

// MenuUpdateRequest defines model for MenuUpdateRequest.
type MenuUpdateRequest struct {
	Abbr  string             `json:"abbr"`
	Id    openapi_types.UUID `json:"id"`
	Items []MenuItemRequest  `json:"items"`
	Key   string             `json:"key"`
	Name  string             `json:"name"`
	Price int                `json:"price"`
}

// OrderCreateRequest defines model for OrderCreateRequest.
type OrderCreateRequest struct {
	BillingAmount     int                     `json:"billing_amount"`
	Comments          *[]CommentCreateRequest `json:"comments,omitempty"`
	DiscountOrderCups *int                    `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int                    `json:"discount_order_id"`
	MenuIds           []MenuInfoCreate        `json:"menu_ids"`
	OrderId           int                     `json:"order_id"`
	Received          int                     `json:"received"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	BillingAmount     int                `json:"billing_amount"`
	Comments          *[]CommentResponse `json:"comments,omitempty"`
	CreatedAt         time.Time          `json:"created_at"`
	DiscountOrderCups *int               `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int               `json:"discount_order_id"`
	Id                openapi_types.UUID `json:"id"`
	Menus             []MenuInfo         `json:"menus"`
	OrderId           int                `json:"order_id"`
	ReadyAt           *time.Time         `json:"ready_at"`
	Received          int                `json:"received"`
	ServedAt          *time.Time         `json:"served_at"`
}

// OrderUpdateRequest defines model for OrderUpdateRequest.
type OrderUpdateRequest struct {
	BillingAmount     int                `json:"billing_amount"`
	DiscountOrderCups *int               `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int               `json:"discount_order_id"`
	Id                openapi_types.UUID `json:"id"`
	MenuIds           []MenuInfoCreate   `json:"menu_ids"`
	OrderId           int                `json:"order_id"`
	ReadyAt           *time.Time         `json:"ready_at"`
	Received          int                `json:"received"`
	ServedAt          *time.Time         `json:"served_at"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Database  string    `json:"database"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// UpsertColorSettingJSONRequestBody defines body for UpsertColorSetting for application/json ContentType.
type UpsertColorSettingJSONRequestBody = ColorSettingUpsertRequest

// CreateItemTypeJSONRequestBody defines body for CreateItemType for application/json ContentType.
type CreateItemTypeJSONRequestBody = ItemTypeCreateRequest

// UpdateItemTypeJSONRequestBody defines body for UpdateItemType for application/json ContentType.
type UpdateItemTypeJSONRequestBody = ItemTypeUpdateRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = ItemCreateRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = ItemUpdateRequest

// UpdateMasterStateJSONRequestBody defines body for UpdateMasterState for application/json ContentType.
type UpdateMasterStateJSONRequestBody = MasterStateUpdateRequest

// CreateMenuJSONRequestBody defines body for CreateMenu for application/json ContentType.
type CreateMenuJSONRequestBody = MenuCreateRequest

// UpdateMenuJSONRequestBody defines body for UpdateMenu for application/json ContentType.
type UpdateMenuJSONRequestBody = MenuUpdateRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderCreateRequest

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody = OrderUpdateRequest

// CreateOrderCommentJSONRequestBody defines body for CreateOrderComment for application/json ContentType.
type CreateOrderCommentJSONRequestBody = CommentCreateRequest
