// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ColorScreen.
const (
	ColorScreenMaster ColorScreen = "master"
	ColorScreenServe  ColorScreen = "serve"
)

// Defines values for ColorTargetType.
const (
	ColorTargetTypeItem     ColorTargetType = "Item"
	ColorTargetTypeItemType ColorTargetType = "ItemType"
)

// Defines values for InventoryLevel.
const (
	InventoryLevelCritical  InventoryLevel = "critical"
	InventoryLevelOk        InventoryLevel = "ok"
	InventoryLevelUntracked InventoryLevel = "untracked"
	InventoryLevelWarning   InventoryLevel = "warning"
)

// Defines values for PaymentMethod.
const (
	Cash   PaymentMethod = "cash"
	Square PaymentMethod = "square"
)

// Defines values for SquareCheckoutOutcome.
const (
	Attention SquareCheckoutOutcome = "attention"
	Failed    SquareCheckoutOutcome = "failed"
	Paid      SquareCheckoutOutcome = "paid"
	Pending   SquareCheckoutOutcome = "pending"
)

// Defines values for SquarePaymentType.
const (
	CARDPRESENT SquarePaymentType = "CARD_PRESENT"
	FELICAALL   SquarePaymentType = "FELICA_ALL"
	QRCODE      SquarePaymentType = "QR_CODE"
)

// Defines values for StockEventKind.
const (
	StockEventKindAdjust  StockEventKind = "adjust"
	StockEventKindCount   StockEventKind = "count"
	StockEventKindReceipt StockEventKind = "receipt"
)

// Defines values for StockResourceKind.
const (
	StockResourceKindBean StockResourceKind = "bean"
	StockResourceKindCup  StockResourceKind = "cup"
)

// CashierStateResponse defines model for CashierStateResponse.
type CashierStateResponse struct {
	// EdittingOrder レジで編集中の注文。フロントの orderSchema の JSON をそのまま保持し、サーバーは上の階層のキーと型を確かめる以外は中身を解釈しない
	EdittingOrder map[string]interface{} `json:"editting_order"`

	// SubmittedOrderId 直前に確定した注文の ID。編集中は null
	SubmittedOrderId *openapi_types.UUID `json:"submitted_order_id"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

// CashierStateUpdateRequest defines model for CashierStateUpdateRequest.
type CashierStateUpdateRequest struct {
	EdittingOrder    map[string]interface{} `json:"editting_order"`
	SubmittedOrderId *openapi_types.UUID    `json:"submitted_order_id"`
}

// ColorScreen 背景色を適用する画面
type ColorScreen string

// ColorSettingResponse defines model for ColorSettingResponse.
type ColorSettingResponse struct {
	Color string             `json:"color"`
	Id    openapi_types.UUID `json:"id"`

	// Screen 背景色を適用する画面
	Screen ColorScreen `json:"screen"`

	// TargetId Item または ItemType の ID
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType 背景色を設定する対象の種類
	TargetType ColorTargetType `json:"target_type"`
}

// ColorSettingUpsertRequest defines model for ColorSettingUpsertRequest.
type ColorSettingUpsertRequest struct {
	Color string `json:"color"`

	// Screen 背景色を適用する画面
	Screen ColorScreen `json:"screen"`

	// TargetId Item または ItemType の ID
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType 背景色を設定する対象の種類
	TargetType ColorTargetType `json:"target_type"`
}

// ColorTargetType 背景色を設定する対象の種類
type ColorTargetType string

// CommentCreateRequest defines model for CommentCreateRequest.
type CommentCreateRequest struct {
	Author string `json:"author"`
	Text   string `json:"text"`
}

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	Author    string             `json:"author"`
	CreatedAt time.Time          `json:"created_at"`
	OrderId   openapi_types.UUID `json:"order_id"`
	Text      string             `json:"text"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// InventoryLevel untracked は棚卸し・入荷がまだ一度も無い
type InventoryLevel string

// InventoryRemindResponse defines model for InventoryRemindResponse.
type InventoryRemindResponse struct {
	Reason *string `json:"reason,omitempty"`
	Sent   bool    `json:"sent"`
}

// InventoryStatus defines model for InventoryStatus.
type InventoryStatus struct {
	// Consumed counted_at 以降の注文での消費量
	Consumed float64 `json:"consumed"`

	// CountedAt 最後の棚卸し。無ければ最初の入荷
	CountedAt       *time.Time `json:"counted_at"`
	CountedQuantity *float64   `json:"counted_quantity"`

	// Level untracked は棚卸し・入荷がまだ一度も無い
	Level InventoryLevel `json:"level"`

	// Received counted_at 以降の入荷・調整の合計
	Received          float64               `json:"received"`
	Remaining         *float64              `json:"remaining"`
	RemainingServings *float64              `json:"remaining_servings"`
	Resource          StockResourceResponse `json:"resource"`

	// Servings counted_at 以降に売れた杯数
	Servings int `json:"servings"`

	// ServingsLastHour 直近1時間に売れた杯数
	ServingsLastHour int `json:"servings_last_hour"`
}

// ItemCreateRequest defines model for ItemCreateRequest.
type ItemCreateRequest struct {
	Abbr       string             `json:"abbr"`
	ItemTypeId openapi_types.UUID `json:"item_type_id"`
	Name       string             `json:"name"`
}

// ItemResponse defines model for ItemResponse.
type ItemResponse struct {
	Abbr     string             `json:"abbr"`
	Id       openapi_types.UUID `json:"id"`
	ItemType ItemTypeResponse   `json:"item_type"`
	Name     string             `json:"name"`
}

// ItemTypeCreateRequest defines model for ItemTypeCreateRequest.
type ItemTypeCreateRequest struct {
	DisplayName string `json:"display_name"`
	Name        string `json:"name"`
}

// ItemTypeResponse defines model for ItemTypeResponse.
type ItemTypeResponse struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// ItemTypeUpdateRequest defines model for ItemTypeUpdateRequest.
type ItemTypeUpdateRequest struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// ItemUpdateRequest defines model for ItemUpdateRequest.
type ItemUpdateRequest struct {
	Abbr       string             `json:"abbr"`
	Id         openapi_types.UUID `json:"id"`
	ItemTypeId openapi_types.UUID `json:"item_type_id"`
	Name       string             `json:"name"`
}

// MasterStateResponse defines model for MasterStateResponse.
type MasterStateResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Type      string    `json:"type"`
}

// MasterStateUpdateRequest defines model for MasterStateUpdateRequest.
type MasterStateUpdateRequest struct {
	Type string `json:"type"`
}

// MenuCreateRequest defines model for MenuCreateRequest.
type MenuCreateRequest struct {
	Abbr  string            `json:"abbr"`
	Items []MenuItemRequest `json:"items"`
	Key   string            `json:"key"`
	Name  string            `json:"name"`
	Price int               `json:"price"`
}

// MenuInfo defines model for MenuInfo.
type MenuInfo struct {
	Assignee *string `json:"assignee"`

	// Id 注文明細ID
	Id   openapi_types.UUID `json:"id"`
	Menu MenuResponse       `json:"menu"`

	// MenuName 注文時点のメニュー名
	MenuName string `json:"menu_name"`

	// UnitPrice 注文時点のメニュー価格
	UnitPrice int `json:"unit_price"`
}

// MenuInfoCreate defines model for MenuInfoCreate.
type MenuInfoCreate struct {
	Assignee *string            `json:"assignee"`
	MenuId   openapi_types.UUID `json:"menu_id"`

	// OrderMenuId 更新時に残す既存明細のID。新規明細では省略する。価格・名称はサーバーが保存する。
	OrderMenuId *openapi_types.UUID `json:"order_menu_id,omitempty"`
}

// MenuItemRequest defines model for MenuItemRequest.
type MenuItemRequest struct {
	ItemId   openapi_types.UUID `json:"item_id"`
	Quantity int                `json:"quantity"`
}

// MenuItemResponse defines model for MenuItemResponse.
type MenuItemResponse struct {
	Item     ItemResponse `json:"item"`
	Quantity int          `json:"quantity"`
}

// MenuResponse defines model for MenuResponse.
type MenuResponse struct {
	Abbr  string             `json:"abbr"`
	Id    openapi_types.UUID `json:"id"`
	Items []MenuItemResponse `json:"items"`
	Key   string             `json:"key"`
	Name  string             `json:"name"`
	Price int                `json:"price"`
}

// MenuUpdateRequest defines model for MenuUpdateRequest.
type MenuUpdateRequest struct {
	Abbr  string             `json:"abbr"`
	Id    openapi_types.UUID `json:"id"`
	Items []MenuItemRequest  `json:"items"`
	Key   string             `json:"key"`
	Name  string             `json:"name"`
	Price int                `json:"price"`
}

// OrderCreateRequest defines model for OrderCreateRequest.
type OrderCreateRequest struct {
	BillingAmount     int                     `json:"billing_amount"`
	Comments          *[]CommentCreateRequest `json:"comments,omitempty"`
	DiscountOrderCups *int                    `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int                    `json:"discount_order_id"`
	MenuIds           []MenuInfoCreate        `json:"menu_ids"`
	OrderId           int                     `json:"order_id"`

	// PaymentMethod 支払い方法。square は Square Terminal での決済（カード・電子マネー・QR）
	PaymentMethod *PaymentMethod `json:"payment_method,omitempty"`
	Received      int            `json:"received"`

	// SquareCheckoutId payment_method が square のとき必須。COMPLETED で金額が billing_amount と一致し、まだどの注文にも使われていない決済依頼の id。
	SquareCheckoutId *openapi_types.UUID `json:"square_checkout_id"`
}

// OrderCupResponse defines model for OrderCupResponse.
type OrderCupResponse struct {
	Id   openapi_types.UUID `json:"id"`
	Item ItemResponse       `json:"item"`

	// OrderMenuId このカップを含む注文明細のID（MenuInfo.id）
	OrderMenuId openapi_types.UUID `json:"order_menu_id"`

	// ReadyAt このカップが準備完了になった時刻。未準備なら null
	ReadyAt *time.Time `json:"ready_at"`

	// ServedAt このカップを提供した時刻。未提供なら null
	ServedAt *time.Time `json:"served_at"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	BillingAmount int                `json:"billing_amount"`
	Comments      *[]CommentResponse `json:"comments,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`

	// Cups 注文のカップ（1杯ずつ）。注文した順に並ぶ。グッズだけの注文では空
	Cups              []OrderCupResponse `json:"cups"`
	DiscountOrderCups *int               `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int               `json:"discount_order_id"`
	Id                openapi_types.UUID `json:"id"`
	Menus             []MenuInfo         `json:"menus"`
	OrderId           int                `json:"order_id"`

	// PaymentMethod 支払い方法。square は Square Terminal での決済（カード・電子マネー・QR）
	PaymentMethod PaymentMethod `json:"payment_method"`
	ReadyAt       *time.Time    `json:"ready_at"`
	Received      int           `json:"received"`
	ServedAt      *time.Time    `json:"served_at"`
}

// OrderUpdateRequest defines model for OrderUpdateRequest.
type OrderUpdateRequest struct {
	BillingAmount     int                `json:"billing_amount"`
	DiscountOrderCups *int               `json:"discount_order_cups,omitempty"`
	DiscountOrderId   *int               `json:"discount_order_id"`
	Id                openapi_types.UUID `json:"id"`
	MenuIds           []MenuInfoCreate   `json:"menu_ids"`
	OrderId           int                `json:"order_id"`
	ReadyAt           *time.Time         `json:"ready_at"`
	Received          int                `json:"received"`
	ServedAt          *time.Time         `json:"served_at"`
}

// PaymentMethod 支払い方法。square は Square Terminal での決済（カード・電子マネー・QR）
type PaymentMethod string

// SquareCheckoutConflictResponse defines model for SquareCheckoutConflictResponse.
type SquareCheckoutConflictResponse struct {
	Checkout SquareCheckoutResponse `json:"checkout"`
	Error    string                 `json:"error"`
}

// SquareCheckoutCreateRequest defines model for SquareCheckoutCreateRequest.
type SquareCheckoutCreateRequest struct {
	// Amount 請求額（円）
	Amount int `json:"amount"`

	// IdempotencyKey レジが決済ごとに作る一意な値（UUID）。再送しても二重に決済画面が出ないようにする
	IdempotencyKey string `json:"idempotency_key"`

	// OrderNumber 依頼時点の注文番号（端末のメモと照合の表示に使う）
	OrderNumber *int `json:"order_number"`

	// PaymentType Square Terminal に出す決済画面の種類（Square の payment_type をそのまま使う）
	PaymentType SquarePaymentType `json:"payment_type"`
}

// SquareCheckoutOutcome レジが次に何をすべきかをサーバーが判定したもの。
//   - pending: まだ決まっていない。待つ
//   - paid: 支払い済みで、受取額も依頼額と一致した。注文を送ってよい
//   - failed: 取り消された・失敗した。お金は受け取っていない
//   - attention: 完了したが受取額が依頼額と合わないなど、人が Square の管理画面で確かめる必要がある
type SquareCheckoutOutcome string

// SquareCheckoutResponse defines model for SquareCheckoutResponse.
type SquareCheckoutResponse struct {
	Amount       int     `json:"amount"`
	CancelReason *string `json:"cancel_reason"`

	// CheckoutId Square の TerminalCheckout の id
	CheckoutId   *string            `json:"checkout_id"`
	CreatedAt    time.Time          `json:"created_at"`
	ErrorMessage *string            `json:"error_message"`
	Id           openapi_types.UUID `json:"id"`

	// OrderId この決済で作った注文。まだ無ければ null
	OrderId     *openapi_types.UUID `json:"order_id"`
	OrderNumber *int                `json:"order_number"`

	// Outcome レジが次に何をすべきかをサーバーが判定したもの。
	//   - pending: まだ決まっていない。待つ
	//   - paid: 支払い済みで、受取額も依頼額と一致した。注文を送ってよい
	//   - failed: 取り消された・失敗した。お金は受け取っていない
	//   - attention: 完了したが受取額が依頼額と合わないなど、人が Square の管理画面で確かめる必要がある
	Outcome SquareCheckoutOutcome `json:"outcome"`

	// PaidAmount 完了後に Payments API で確かめた受取額（円）
	PaidAmount  *int     `json:"paid_amount"`
	PaymentIds  []string `json:"payment_ids"`
	PaymentType string   `json:"payment_type"`

	// Status Square の status（PENDING / IN_PROGRESS / CANCEL_REQUESTED / CANCELED / COMPLETED）。依頼前は CREATING、依頼に失敗したら ERROR
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SquarePaymentType Square Terminal に出す決済画面の種類（Square の payment_type をそのまま使う）
type SquarePaymentType string

// SquareStatusResponse defines model for SquareStatusResponse.
type SquareStatusResponse struct {
	Enabled bool `json:"enabled"`

	// Environment production か sandbox
	Environment    string `json:"environment"`
	WebhookEnabled bool   `json:"webhook_enabled"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Database  string    `json:"database"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// StockEventCreateRequest defines model for StockEventCreateRequest.
type StockEventCreateRequest struct {
	Kind     StockEventKind `json:"kind"`
	Note     *string        `json:"note,omitempty"`
	Quantity float64        `json:"quantity"`
}

// StockEventCreateResponse defines model for StockEventCreateResponse.
type StockEventCreateResponse struct {
	// ActualPerServing 前回の棚卸しから今回までの実測の1杯あたり使用量（count のときだけ）
	ActualPerServing *float64 `json:"actual_per_serving"`

	// Estimated 記録する直前の推定残量（count のときの答え合わせ用）
	Estimated *float64           `json:"estimated"`
	Event     StockEventResponse `json:"event"`
}

// StockEventKind defines model for StockEventKind.
type StockEventKind string

// StockEventResponse defines model for StockEventResponse.
type StockEventResponse struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Kind       StockEventKind     `json:"kind"`
	Note       *string            `json:"note,omitempty"`
	Quantity   float64            `json:"quantity"`
	ResourceId openapi_types.UUID `json:"resource_id"`
}

// StockResourceKind defines model for StockResourceKind.
type StockResourceKind string

// StockResourceRequest defines model for StockResourceRequest.
type StockResourceRequest struct {
	// Buffer 最低限残したい杯数。これを切ると危険扱い
	Buffer int               `json:"buffer"`
	Kind   StockResourceKind `json:"kind"`
	Name   string            `json:"name"`

	// NotifyFrom 残りがこの杯数を切ったら通知を始める
	NotifyFrom int `json:"notify_from"`

	// NotifyStep notify_from から何杯減るごとに通知するか
	NotifyStep int `json:"notify_step"`

	// PerServing 1杯あたりの量。残量を杯数に換算するのに使う（カップ 1、豆 15）
	PerServing float64 `json:"per_serving"`

	// Unit 数える単位（個 / g）
	Unit string `json:"unit"`
}

// StockResourceResponse defines model for StockResourceResponse.
type StockResourceResponse struct {
	// Buffer 最低限残したい杯数。これを切ると危険扱い
	Buffer int                `json:"buffer"`
	Id     openapi_types.UUID `json:"id"`
	Kind   StockResourceKind  `json:"kind"`
	Name   string             `json:"name"`

	// NotifyFrom 残りがこの杯数を切ったら通知を始める
	NotifyFrom int `json:"notify_from"`

	// NotifyStep notify_from から何杯減るごとに通知するか
	NotifyStep int `json:"notify_step"`

	// PerServing 1杯あたりの量。残量を杯数に換算するのに使う（カップ 1、豆 15）
	PerServing float64 `json:"per_serving"`

	// Unit 数える単位（個 / g）
	Unit string `json:"unit"`
}

// StockUsage defines model for StockUsage.
type StockUsage struct {
	// Amount アイテム1杯で使う量（カップ 1、豆 15 など）
	Amount     float64            `json:"amount"`
	ItemId     openapi_types.UUID `json:"item_id"`
	ResourceId openapi_types.UUID `json:"resource_id"`
}

// ReplaceStockUsagesJSONBody defines parameters for ReplaceStockUsages.
type ReplaceStockUsagesJSONBody = []StockUsage

// ReceiveSquareWebhookJSONBody defines parameters for ReceiveSquareWebhook.
type ReceiveSquareWebhookJSONBody = map[string]interface{}

// UpdateCashierStateJSONRequestBody defines body for UpdateCashierState for application/json ContentType.
type UpdateCashierStateJSONRequestBody = CashierStateUpdateRequest

// UpsertColorSettingJSONRequestBody defines body for UpsertColorSetting for application/json ContentType.
type UpsertColorSettingJSONRequestBody = ColorSettingUpsertRequest

// CreateStockResourceJSONRequestBody defines body for CreateStockResource for application/json ContentType.
type CreateStockResourceJSONRequestBody = StockResourceRequest

// UpdateStockResourceJSONRequestBody defines body for UpdateStockResource for application/json ContentType.
type UpdateStockResourceJSONRequestBody = StockResourceRequest

// CreateStockEventJSONRequestBody defines body for CreateStockEvent for application/json ContentType.
type CreateStockEventJSONRequestBody = StockEventCreateRequest

// ReplaceStockUsagesJSONRequestBody defines body for ReplaceStockUsages for application/json ContentType.
type ReplaceStockUsagesJSONRequestBody = ReplaceStockUsagesJSONBody

// CreateItemTypeJSONRequestBody defines body for CreateItemType for application/json ContentType.
type CreateItemTypeJSONRequestBody = ItemTypeCreateRequest

// UpdateItemTypeJSONRequestBody defines body for UpdateItemType for application/json ContentType.
type UpdateItemTypeJSONRequestBody = ItemTypeUpdateRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = ItemCreateRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = ItemUpdateRequest

// UpdateMasterStateJSONRequestBody defines body for UpdateMasterState for application/json ContentType.
type UpdateMasterStateJSONRequestBody = MasterStateUpdateRequest

// CreateMenuJSONRequestBody defines body for CreateMenu for application/json ContentType.
type CreateMenuJSONRequestBody = MenuCreateRequest

// UpdateMenuJSONRequestBody defines body for UpdateMenu for application/json ContentType.
type UpdateMenuJSONRequestBody = MenuUpdateRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderCreateRequest

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody = OrderUpdateRequest

// CreateOrderCommentJSONRequestBody defines body for CreateOrderComment for application/json ContentType.
type CreateOrderCommentJSONRequestBody = CommentCreateRequest

// CreateSquareCheckoutJSONRequestBody defines body for CreateSquareCheckout for application/json ContentType.
type CreateSquareCheckoutJSONRequestBody = SquareCheckoutCreateRequest

// ReceiveSquareWebhookJSONRequestBody defines body for ReceiveSquareWebhook for application/json ContentType.
type ReceiveSquareWebhookJSONRequestBody = ReceiveSquareWebhookJSONBody
