// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handlers

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CaOS の本番の抽出時間の集計（ドリッパー・時間帯・担当者ごとの係数）
	// (GET /api/caos/brew-stats)
	GetCaosBrewStats(c *gin.Context)
	// CaOS が決めたことを注文のカップに書く
	// (PUT /api/caos/cups)
	WriteCaosCups(c *gin.Context)
	// CaOS の「次へ」
	// (POST /api/caos/drippers/{dripper}/next)
	AdvanceCaosDripper(c *gin.Context, dripper int)
	// カップを緊急（入れ直し）にする
	// (POST /api/caos/emergency)
	MarkCaosEmergency(c *gin.Context)
	// CaOS の 2 つのドリッパーの担当者を入れ替える
	// (POST /api/caos/lanes/swap)
	SwapCaosLanes(c *gin.Context)
	// CaOS のドリッパーの担当者を替える（交代）
	// (PUT /api/caos/lanes/{dripper})
	PutCaosLane(c *gin.Context, dripper int)
	// CaOS の「1つ戻す」
	// (POST /api/caos/undo)
	UndoCaosCups(c *gin.Context)
	// レジ状態取得
	// (GET /api/cashier-state)
	GetCashierState(c *gin.Context)
	// レジ状態更新
	// (PUT /api/cashier-state)
	UpdateCashierState(c *gin.Context)
	// 背景色設定一覧取得
	// (GET /api/color-settings)
	GetColorSettings(c *gin.Context)
	// 背景色設定の作成・更新
	// (PUT /api/color-settings)
	UpsertColorSetting(c *gin.Context)
	// 背景色設定削除
	// (DELETE /api/color-settings/{id})
	DeleteColorSetting(c *gin.Context, id openapi_types.UUID)
	// 在庫の残量一覧
	// (GET /api/inventory)
	GetInventory(c *gin.Context)
	// 残量確認のリマインドを Slack に送る
	// (POST /api/inventory/remind)
	RemindInventory(c *gin.Context)
	// 在庫対象の作成
	// (POST /api/inventory/resources)
	CreateStockResource(c *gin.Context)
	// 在庫対象の削除
	// (DELETE /api/inventory/resources/{id})
	DeleteStockResource(c *gin.Context, id openapi_types.UUID)
	// 在庫対象の更新
	// (PUT /api/inventory/resources/{id})
	UpdateStockResource(c *gin.Context, id openapi_types.UUID)
	// 棚卸し・入荷・調整の記録
	// (POST /api/inventory/resources/{id}/events)
	CreateStockEvent(c *gin.Context, id openapi_types.UUID)
	// アイテム1杯あたりの使用量一覧
	// (GET /api/inventory/usages)
	GetStockUsages(c *gin.Context)
	// アイテム1杯あたりの使用量をまとめて置き換える
	// (PUT /api/inventory/usages)
	ReplaceStockUsages(c *gin.Context)
	// アイテムタイプ一覧取得
	// (GET /api/item-types)
	GetItemTypes(c *gin.Context)
	// アイテムタイプ作成
	// (POST /api/item-types)
	CreateItemType(c *gin.Context)
	// アイテムタイプ削除
	// (DELETE /api/item-types/{id})
	DeleteItemType(c *gin.Context, id openapi_types.UUID)
	// idからアイテムタイプ情報取得
	// (GET /api/item-types/{id})
	GetItemType(c *gin.Context, id openapi_types.UUID)
	// アイテム情報更新
	// (PUT /api/item-types/{id})
	UpdateItemType(c *gin.Context, id openapi_types.UUID)
	// アイテム一覧取得
	// (GET /api/items)
	GetItems(c *gin.Context)
	// アイテム作成
	// (POST /api/items)
	CreateItem(c *gin.Context)
	// アイテム削除
	// (DELETE /api/items/{id})
	DeleteItem(c *gin.Context, id openapi_types.UUID)
	// idからアイテム情報取得
	// (GET /api/items/{id})
	GetItem(c *gin.Context, id openapi_types.UUID)
	// アイテム情報更新
	// (PUT /api/items/{id})
	UpdateItem(c *gin.Context, id openapi_types.UUID)
	// マスターステート取得
	// (GET /api/master-status)
	GetMasterState(c *gin.Context)
	// マスターステート更新
	// (POST /api/master-status)
	UpdateMasterState(c *gin.Context)
	// メニュー一覧取得
	// (GET /api/menus)
	GetMenus(c *gin.Context)
	// メニュー作成
	// (POST /api/menus)
	CreateMenu(c *gin.Context)
	// メニュー削除
	// (DELETE /api/menus/{id})
	DeleteMenu(c *gin.Context, id openapi_types.UUID)
	// メニュー取得
	// (GET /api/menus/{id})
	GetMenu(c *gin.Context, id openapi_types.UUID)
	// メニュー更新
	// (PUT /api/menus/{id})
	UpdateMenu(c *gin.Context, id openapi_types.UUID)
	// オーダー一覧取得
	// (GET /api/orders)
	GetOrders(c *gin.Context)
	// オーダー作成
	// (POST /api/orders)
	CreateOrder(c *gin.Context)
	// オーダー削除
	// (DELETE /api/orders/{id})
	DeleteOrder(c *gin.Context, id openapi_types.UUID)
	// idからオーダー情報取得
	// (GET /api/orders/{id})
	GetOrder(c *gin.Context, id openapi_types.UUID)
	// オーダー情報更新
	// (PUT /api/orders/{id})
	UpdateOrder(c *gin.Context, id openapi_types.UUID)
	// 特定オーダーのコメント一覧取得
	// (GET /api/orders/{id}/comments)
	GetOrderComments(c *gin.Context, id openapi_types.UUID)
	// オーダーにコメント追加
	// (POST /api/orders/{id}/comments)
	CreateOrderComment(c *gin.Context, id openapi_types.UUID)
	// 緊急のシールを印刷する役を取る
	// (POST /api/orders/{id}/cups/{cupId}/emergency-label/claim)
	ClaimEmergencyLabel(c *gin.Context, id openapi_types.UUID, cupId openapi_types.UUID)
	// 緊急のシールの印刷に失敗したので、印刷した時刻を空に戻す
	// (POST /api/orders/{id}/cups/{cupId}/emergency-label/release)
	ReleaseEmergencyLabel(c *gin.Context, id openapi_types.UUID, cupId openapi_types.UUID)
	// カップを準備完了にする
	// (PATCH /api/orders/{id}/cups/{cupId}/ready)
	MarkOrderCupReady(c *gin.Context, id openapi_types.UUID, cupId openapi_types.UUID)
	// カップを提供完了にする
	// (PATCH /api/orders/{id}/cups/{cupId}/served)
	MarkOrderCupServe(c *gin.Context, id openapi_types.UUID, cupId openapi_types.UUID)
	// オーダーを準備完了にする
	// (PATCH /api/orders/{id}/ready)
	MarkOrderReady(c *gin.Context, id openapi_types.UUID)
	// オーダーを提供完了にする
	// (PATCH /api/orders/{id}/served)
	MarkOrderServe(c *gin.Context, id openapi_types.UUID)
	// サーバーステータス取得
	// (GET /status)
	GetStatus(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCaosBrewStats operation middleware
func (siw *ServerInterfaceWrapper) GetCaosBrewStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCaosBrewStats(c)
}

// WriteCaosCups operation middleware
func (siw *ServerInterfaceWrapper) WriteCaosCups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.WriteCaosCups(c)
}

// AdvanceCaosDripper operation middleware
func (siw *ServerInterfaceWrapper) AdvanceCaosDripper(c *gin.Context) {

	var err error

	// ------------- Path parameter "dripper" -------------
	var dripper int

	err = runtime.BindStyledParameterWithOptions("simple", "dripper", c.Param("dripper"), &dripper, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dripper: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdvanceCaosDripper(c, dripper)
}

// MarkCaosEmergency operation middleware
func (siw *ServerInterfaceWrapper) MarkCaosEmergency(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MarkCaosEmergency(c)
}

// SwapCaosLanes operation middleware
func (siw *ServerInterfaceWrapper) SwapCaosLanes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SwapCaosLanes(c)
}

// PutCaosLane operation middleware
func (siw *ServerInterfaceWrapper) PutCaosLane(c *gin.Context) {

	var err error

	// ------------- Path parameter "dripper" -------------
	var dripper int

	err = runtime.BindStyledParameterWithOptions("simple", "dripper", c.Param("dripper"), &dripper, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dripper: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCaosLane(c, dripper)
}

// UndoCaosCups operation middleware
func (siw *ServerInterfaceWrapper) UndoCaosCups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UndoCaosCups(c)
}

// GetCashierState operation middleware
func (siw *ServerInterfaceWrapper) GetCashierState(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCashierState(c)
}

// UpdateCashierState operation middleware
func (siw *ServerInterfaceWrapper) UpdateCashierState(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCashierState(c)
}

// GetColorSettings operation middleware
func (siw *ServerInterfaceWrapper) GetColorSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetColorSettings(c)
}

// UpsertColorSetting operation middleware
func (siw *ServerInterfaceWrapper) UpsertColorSetting(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertColorSetting(c)
}

// DeleteColorSetting operation middleware
func (siw *ServerInterfaceWrapper) DeleteColorSetting(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteColorSetting(c, id)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c)
}

// RemindInventory operation middleware
func (siw *ServerInterfaceWrapper) RemindInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemindInventory(c)
}

// CreateStockResource operation middleware
func (siw *ServerInterfaceWrapper) CreateStockResource(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStockResource(c)
}

// DeleteStockResource operation middleware
func (siw *ServerInterfaceWrapper) DeleteStockResource(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteStockResource(c, id)
}

// UpdateStockResource operation middleware
func (siw *ServerInterfaceWrapper) UpdateStockResource(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStockResource(c, id)
}

// CreateStockEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateStockEvent(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStockEvent(c, id)
}

// GetStockUsages operation middleware
func (siw *ServerInterfaceWrapper) GetStockUsages(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStockUsages(c)
}

// ReplaceStockUsages operation middleware
func (siw *ServerInterfaceWrapper) ReplaceStockUsages(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceStockUsages(c)
}

// GetItemTypes operation middleware
func (siw *ServerInterfaceWrapper) GetItemTypes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItemTypes(c)
}

// CreateItemType operation middleware
func (siw *ServerInterfaceWrapper) CreateItemType(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItemType(c)
}

// DeleteItemType operation middleware
func (siw *ServerInterfaceWrapper) DeleteItemType(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItemType(c, id)
}

// GetItemType operation middleware
func (siw *ServerInterfaceWrapper) GetItemType(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItemType(c, id)
}

// UpdateItemType operation middleware
func (siw *ServerInterfaceWrapper) UpdateItemType(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateItemType(c, id)
}

// GetItems operation middleware
func (siw *ServerInterfaceWrapper) GetItems(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItems(c)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItem(c, id)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, id)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateItem(c, id)
}

// GetMasterState operation middleware
func (siw *ServerInterfaceWrapper) GetMasterState(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMasterState(c)
}

// UpdateMasterState operation middleware
func (siw *ServerInterfaceWrapper) UpdateMasterState(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMasterState(c)
}

// GetMenus operation middleware
func (siw *ServerInterfaceWrapper) GetMenus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMenus(c)
}

// CreateMenu operation middleware
func (siw *ServerInterfaceWrapper) CreateMenu(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMenu(c)
}

// DeleteMenu operation middleware
func (siw *ServerInterfaceWrapper) DeleteMenu(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMenu(c, id)
}

// GetMenu operation middleware
func (siw *ServerInterfaceWrapper) GetMenu(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMenu(c, id)
}

// UpdateMenu operation middleware
func (siw *ServerInterfaceWrapper) UpdateMenu(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMenu(c, id)
}

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrders(c)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrder(c)
}

// DeleteOrder operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteOrder(c, id)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrder(c, id)
}

// UpdateOrder operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrder(c, id)
}

// GetOrderComments operation middleware
func (siw *ServerInterfaceWrapper) GetOrderComments(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrderComments(c, id)
}

// CreateOrderComment operation middleware
func (siw *ServerInterfaceWrapper) CreateOrderComment(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrderComment(c, id)
}

// ClaimEmergencyLabel operation middleware
func (siw *ServerInterfaceWrapper) ClaimEmergencyLabel(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cupId" -------------
	var cupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cupId", c.Param("cupId"), &cupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ClaimEmergencyLabel(c, id, cupId)
}

// ReleaseEmergencyLabel operation middleware
func (siw *ServerInterfaceWrapper) ReleaseEmergencyLabel(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cupId" -------------
	var cupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cupId", c.Param("cupId"), &cupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReleaseEmergencyLabel(c, id, cupId)
}

// MarkOrderCupReady operation middleware
func (siw *ServerInterfaceWrapper) MarkOrderCupReady(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cupId" -------------
	var cupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cupId", c.Param("cupId"), &cupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MarkOrderCupReady(c, id, cupId)
}

// MarkOrderCupServe operation middleware
func (siw *ServerInterfaceWrapper) MarkOrderCupServe(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cupId" -------------
	var cupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "cupId", c.Param("cupId"), &cupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MarkOrderCupServe(c, id, cupId)
}

// MarkOrderReady operation middleware
func (siw *ServerInterfaceWrapper) MarkOrderReady(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MarkOrderReady(c, id)
}

// MarkOrderServe operation middleware
func (siw *ServerInterfaceWrapper) MarkOrderServe(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MarkOrderServe(c, id)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatus(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/caos/brew-stats", wrapper.GetCaosBrewStats)
	router.PUT(options.BaseURL+"/api/caos/cups", wrapper.WriteCaosCups)
	router.POST(options.BaseURL+"/api/caos/drippers/:dripper/next", wrapper.AdvanceCaosDripper)
	router.POST(options.BaseURL+"/api/caos/emergency", wrapper.MarkCaosEmergency)
	router.POST(options.BaseURL+"/api/caos/lanes/swap", wrapper.SwapCaosLanes)
	router.PUT(options.BaseURL+"/api/caos/lanes/:dripper", wrapper.PutCaosLane)
	router.POST(options.BaseURL+"/api/caos/undo", wrapper.UndoCaosCups)
	router.GET(options.BaseURL+"/api/cashier-state", wrapper.GetCashierState)
	router.PUT(options.BaseURL+"/api/cashier-state", wrapper.UpdateCashierState)
	router.GET(options.BaseURL+"/api/color-settings", wrapper.GetColorSettings)
	router.PUT(options.BaseURL+"/api/color-settings", wrapper.UpsertColorSetting)
	router.DELETE(options.BaseURL+"/api/color-settings/:id", wrapper.DeleteColorSetting)
	router.GET(options.BaseURL+"/api/inventory", wrapper.GetInventory)
	router.POST(options.BaseURL+"/api/inventory/remind", wrapper.RemindInventory)
	router.POST(options.BaseURL+"/api/inventory/resources", wrapper.CreateStockResource)
	router.DELETE(options.BaseURL+"/api/inventory/resources/:id", wrapper.DeleteStockResource)
	router.PUT(options.BaseURL+"/api/inventory/resources/:id", wrapper.UpdateStockResource)
	router.POST(options.BaseURL+"/api/inventory/resources/:id/events", wrapper.CreateStockEvent)
	router.GET(options.BaseURL+"/api/inventory/usages", wrapper.GetStockUsages)
	router.PUT(options.BaseURL+"/api/inventory/usages", wrapper.ReplaceStockUsages)
	router.GET(options.BaseURL+"/api/item-types", wrapper.GetItemTypes)
	router.POST(options.BaseURL+"/api/item-types", wrapper.CreateItemType)
	router.DELETE(options.BaseURL+"/api/item-types/:id", wrapper.DeleteItemType)
	router.GET(options.BaseURL+"/api/item-types/:id", wrapper.GetItemType)
	router.PUT(options.BaseURL+"/api/item-types/:id", wrapper.UpdateItemType)
	router.GET(options.BaseURL+"/api/items", wrapper.GetItems)
	router.POST(options.BaseURL+"/api/items", wrapper.CreateItem)
	router.DELETE(options.BaseURL+"/api/items/:id", wrapper.DeleteItem)
	router.GET(options.BaseURL+"/api/items/:id", wrapper.GetItem)
	router.PUT(options.BaseURL+"/api/items/:id", wrapper.UpdateItem)
	router.GET(options.BaseURL+"/api/master-status", wrapper.GetMasterState)
	router.POST(options.BaseURL+"/api/master-status", wrapper.UpdateMasterState)
	router.GET(options.BaseURL+"/api/menus", wrapper.GetMenus)
	router.POST(options.BaseURL+"/api/menus", wrapper.CreateMenu)
	router.DELETE(options.BaseURL+"/api/menus/:id", wrapper.DeleteMenu)
	router.GET(options.BaseURL+"/api/menus/:id", wrapper.GetMenu)
	router.PUT(options.BaseURL+"/api/menus/:id", wrapper.UpdateMenu)
	router.GET(options.BaseURL+"/api/orders", wrapper.GetOrders)
	router.POST(options.BaseURL+"/api/orders", wrapper.CreateOrder)
	router.DELETE(options.BaseURL+"/api/orders/:id", wrapper.DeleteOrder)
	router.GET(options.BaseURL+"/api/orders/:id", wrapper.GetOrder)
	router.PUT(options.BaseURL+"/api/orders/:id", wrapper.UpdateOrder)
	router.GET(options.BaseURL+"/api/orders/:id/comments", wrapper.GetOrderComments)
	router.POST(options.BaseURL+"/api/orders/:id/comments", wrapper.CreateOrderComment)
	router.POST(options.BaseURL+"/api/orders/:id/cups/:cupId/emergency-label/claim", wrapper.ClaimEmergencyLabel)
	router.POST(options.BaseURL+"/api/orders/:id/cups/:cupId/emergency-label/release", wrapper.ReleaseEmergencyLabel)
	router.PATCH(options.BaseURL+"/api/orders/:id/cups/:cupId/ready", wrapper.MarkOrderCupReady)
	router.PATCH(options.BaseURL+"/api/orders/:id/cups/:cupId/served", wrapper.MarkOrderCupServe)
	router.PATCH(options.BaseURL+"/api/orders/:id/ready", wrapper.MarkOrderReady)
	router.PATCH(options.BaseURL+"/api/orders/:id/served", wrapper.MarkOrderServe)
	router.GET(options.BaseURL+"/status", wrapper.GetStatus)
}
