/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    /** サーバーステータス取得 */
    get: operations["getStatus"];
  };
  "/api/items": {
    /** アイテム一覧取得 */
    get: operations["getItems"];
    /** アイテム作成 */
    post: operations["createItem"];
  };
  "/api/items/{id}": {
    /** idからアイテム情報取得 */
    get: operations["getItem"];
    /** アイテム情報更新 */
    put: operations["updateItem"];
    /** アイテム削除 */
    delete: operations["deleteItem"];
  };
  "/api/menus": {
    /** メニュー一覧取得 */
    get: operations["getMenus"];
    /** メニュー作成 */
    post: operations["createMenu"];
  };
  "/api/menus/{id}": {
    /** メニュー取得 */
    get: operations["getMenu"];
    /** メニュー更新 */
    put: operations["updateMenu"];
    /** メニュー削除 */
    delete: operations["deleteMenu"];
  };
  "/api/item-types": {
    /** アイテムタイプ一覧取得 */
    get: operations["getItemTypes"];
    /** アイテムタイプ作成 */
    post: operations["createItemType"];
  };
  "/api/item-types/{id}": {
    /** idからアイテムタイプ情報取得 */
    get: operations["getItemType"];
    /** アイテム情報更新 */
    put: operations["updateItemType"];
    /** アイテムタイプ削除 */
    delete: operations["deleteItemType"];
  };
  "/api/color-settings": {
    /** 背景色設定一覧取得 */
    get: operations["getColorSettings"];
    /**
     * 背景色設定の作成・更新
     * @description 対象（target_type, target_id）と画面（screen）の組が既にあれば色を上書きし、無ければ作成する
     */
    put: operations["upsertColorSetting"];
  };
  "/api/color-settings/{id}": {
    /** 背景色設定削除 */
    delete: operations["deleteColorSetting"];
  };
  "/api/orders": {
    /** オーダー一覧取得 */
    get: operations["getOrders"];
    /** オーダー作成 */
    post: operations["createOrder"];
  };
  "/api/orders/{id}": {
    /** idからオーダー情報取得 */
    get: operations["getOrder"];
    /** オーダー情報更新 */
    put: operations["updateOrder"];
    /** オーダー削除 */
    delete: operations["deleteOrder"];
  };
  "/api/orders/{id}/ready": {
    /** オーダーを準備完了にする */
    patch: operations["markOrderReady"];
  };
  "/api/orders/{id}/served": {
    /** オーダーを提供完了にする */
    patch: operations["markOrderServe"];
  };
  "/api/orders/{id}/comments": {
    /** 特定オーダーのコメント一覧取得 */
    get: operations["getOrderComments"];
    /** オーダーにコメント追加 */
    post: operations["createOrderComment"];
  };
  "/api/caos/boards/{day}": {
    /**
     * CaOS の盤面（その日の全カードと版）
     * @description 読む前に、その日の注文と照らし合わせてカードをそろえる。CaOS の画面は、つないだとき・
     * WebSocket の drips_version で手元より新しい版を知ったときに読み直す。
     */
    get: operations["getCaosBoard"];
  };
  "/api/caos/boards/{day}/ops": {
    /**
     * CaOS の盤面への操作
     * @description 割当・戻す・次へ・統合・入れ直し・1つ戻すのどれか 1 つ（name で選ぶ）。1 つの盤面への操作は 1 件ずつ順番に処理する。
     * 注文のカードが全部終わったら、同じトランザクションで注文を準備完了にする（readied）。
     * 変わったカードは WebSocket（/api/ws/orders）の drips でほかの画面にも届く。
     */
    post: operations["applyCaosOp"];
  };
  "/api/master-status": {
    /** マスターステート取得 */
    get: operations["getMasterState"];
    /** マスターステート更新 */
    post: operations["updateMasterState"];
  };
  "/api/inventory": {
    /**
     * 在庫の残量一覧
     * @description 最後の棚卸しからの入荷・注文での消費を差し引いた推定残量。
     */
    get: operations["getInventory"];
  };
  "/api/inventory/resources": {
    /** 在庫対象の作成 */
    post: operations["createStockResource"];
  };
  "/api/inventory/resources/{id}": {
    /** 在庫対象の更新 */
    put: operations["updateStockResource"];
    /** 在庫対象の削除 */
    delete: operations["deleteStockResource"];
  };
  "/api/inventory/resources/{id}/events": {
    /**
     * 棚卸し・入荷・調整の記録
     * @description count は実数で残量を置き換える（0 以上）。receipt は入荷として正の数を足す。adjust は差分として足す（減らすときは負の値、0 は不可）。
     */
    post: operations["createStockEvent"];
  };
  "/api/inventory/usages": {
    /** アイテム1杯あたりの使用量一覧 */
    get: operations["getStockUsages"];
    /** アイテム1杯あたりの使用量をまとめて置き換える */
    put: operations["replaceStockUsages"];
  };
  "/api/inventory/remind": {
    /**
     * 残量確認のリマインドを Slack に送る
     * @description スケジューラから定期的に叩く。次のどちらかを満たさないと 401。
     *   - Authorization: Bearer の Google ID トークン（INVENTORY_REMIND_INVOKER の SA が audience INVENTORY_REMIND_AUDIENCE で発行したもの）。本番の Cloud Scheduler はこちら
     *   - X-Cron-Secret ヘッダーが INVENTORY_CRON_SECRET と一致する。ローカルや手動実行用
     * （ヘッダーをパラメータやセキュリティスキームとして書くと、生成される api_gin.go が models の型を参照できずビルドが通らないので説明だけに留める）
     * 直近に注文が無い（営業していない）ときは送らない。
     */
    post: operations["remindInventory"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StatusResponse: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
      /** @example 1.0.0 */
      version: string;
      /** @example connected */
      database: string;
    };
    ItemResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      item_type: components["schemas"]["ItemTypeResponse"];
    };
    ItemCreateRequest: {
      name: string;
      abbr: string;
      /** Format: uuid */
      item_type_id: string;
    };
    ItemUpdateRequest: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      /** Format: uuid */
      item_type_id: string;
    };
    MenuItemResponse: {
      item: components["schemas"]["ItemResponse"];
      quantity: number;
    };
    MenuItemRequest: {
      /** Format: uuid */
      item_id: string;
      quantity: number;
    };
    MenuResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      price: number;
      key: string;
      items: components["schemas"]["MenuItemResponse"][];
    };
    MenuCreateRequest: {
      name: string;
      abbr: string;
      price: number;
      key: string;
      items: components["schemas"]["MenuItemRequest"][];
    };
    MenuUpdateRequest: components["schemas"]["MenuCreateRequest"] & {
      /** Format: uuid */
      id: string;
    };
    ItemTypeResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
    };
    ItemTypeCreateRequest: {
      name: string;
      display_name: string;
    };
    ItemTypeUpdateRequest: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
    };
    MenuInfo: {
      /**
       * Format: uuid
       * @description 注文明細ID
       */
      id: string;
      /** @description 注文時点のメニュー名 */
      menu_name: string;
      /** @description 注文時点のメニュー価格 */
      unit_price: number;
      menu: components["schemas"]["MenuResponse"];
      assignee: string | null;
    };
    MenuInfoCreate: {
      /**
       * Format: uuid
       * @description 更新時に残す既存明細のID。新規明細では省略する。価格・名称はサーバーが保存する。
       */
      order_menu_id?: string;
      /** Format: uuid */
      menu_id: string;
      assignee: string | null;
    };
    OrderResponse: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received: number;
      discount_order_id?: number | null;
      discount_order_cups?: number;
      menus: components["schemas"]["MenuInfo"][];
      comments?: components["schemas"]["CommentResponse"][];
    };
    OrderCreateRequest: {
      /** @example 1 */
      order_id: number;
      /** @example 500 */
      billing_amount: number;
      /**
       * @default 0
       * @example 500
       */
      received: number;
      discount_order_id?: number | null;
      /** @default 0 */
      discount_order_cups?: number;
      menu_ids: components["schemas"]["MenuInfoCreate"][];
      comments?: components["schemas"]["CommentCreateRequest"][];
    };
    OrderUpdateRequest: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received: number;
      discount_order_id?: number | null;
      discount_order_cups?: number;
      menu_ids: components["schemas"]["MenuInfoCreate"][];
    };
    OrderListItem: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received?: number;
      discount_order_cups?: number;
    };
    CommentCreateRequest: {
      author: string;
      text: string;
    };
    CommentResponse: {
      /** Format: uuid */
      order_id: string;
      author: string;
      text: string;
      /** Format: date-time */
      created_at: string;
    };
    MasterStateResponse: {
      /** Format: date-time */
      created_at: string;
      type: string;
    };
    MasterStateUpdateRequest: {
      type: string;
    };
    /**
     * @description 背景色を設定する対象の種類
     * @enum {string}
     */
    ColorTargetType: "Item" | "ItemType";
    /**
     * @description 背景色を適用する画面
     * @enum {string}
     */
    ColorScreen: "master" | "serve";
    ColorSettingResponse: {
      /** Format: uuid */
      id: string;
      target_type: components["schemas"]["ColorTargetType"];
      /**
       * Format: uuid
       * @description Item または ItemType の ID
       */
      target_id: string;
      screen: components["schemas"]["ColorScreen"];
      /** @example #bfdbfe */
      color: string;
    };
    ColorSettingUpsertRequest: {
      target_type: components["schemas"]["ColorTargetType"];
      /**
       * Format: uuid
       * @description Item または ItemType の ID
       */
      target_id: string;
      screen: components["schemas"]["ColorScreen"];
      /** @example #bfdbfe */
      color: string;
    };
    /** @description 抽出カードの中身の 1 行。注文番号や商品名はカードを作った時点のもの */
    CaosDripLine: {
      /** Format: uuid */
      order_id: string;
      order_no: number;
      /** Format: uuid */
      item_id: string;
      name: string;
      abbr: string;
      /** @description 商品の種類（item_types.name） */
      type: string;
      /** @description POS の指名（前後の空白を落としたもの） */
      nominee: string | null;
      cups: number;
    };
    /**
     * @description unassigned＝未割当 / queued＝担当の待機列 / brewing＝抽出中（1 人 1 枚） / done＝抽出終了
     * @enum {string}
     */
    CaosDripStatus: "unassigned" | "queued" | "brewing" | "done";
    /** @description 抽出カード。1 回のドリップ（最大 2 杯）が 1 枚 */
    CaosDrip: {
      /** Format: uuid */
      id: string;
      status: components["schemas"]["CaosDripStatus"];
      dripper: number | null;
      /**
       * Format: double
       * @description 待機列の並び順（ふだんは注文番号）
       */
      queue_pos: number;
      order_ids: string[];
      lines: components["schemas"]["CaosDripLine"][];
      cups: number;
      /**
       * Format: uuid
       * @description 入れ直しのカードなら、元のカード
       */
      rebrew_of: string | null;
      /** @description 入れ直しのために途中でやめた抽出 */
      interrupted: boolean;
      /** Format: date-time */
      started_at: string | null;
      /** Format: date-time */
      finished_at: string | null;
      /** Format: date-time */
      created_at: string;
      /**
       * Format: date-time
       * @description 「1つ戻す」は、この値が操作の結果と同じとき（ほかの端末が触っていないとき）だけ戻す
       */
      updated_at: string;
    };
    CaosBoard: {
      /** Format: date */
      day: string;
      /**
       * Format: int64
       * @description 盤面の版。カードが変わるたびに 1 ずつ増える
       */
      v: number;
      drips: components["schemas"]["CaosDrip"][];
    };
    /**
     * @description name ごとに使うフィールド：
     * assign（drip_id・dripper）/ unassign（drip_id）/ next（dripper）/ merge（first_id・second_id）/
     * rebrew（source_id・cups・interrupt・dripper（null なら未割当）・queue_pos（null なら元の位置））/
     * restore（before・after・readied）
     */
    CaosOp: {
      /** @enum {string} */
      name: "assign" | "unassign" | "next" | "merge" | "rebrew" | "restore";
      /** Format: uuid */
      drip_id?: string;
      dripper?: number | null;
      /** Format: uuid */
      first_id?: string;
      /** Format: uuid */
      second_id?: string;
      /** Format: uuid */
      source_id?: string;
      /** @description 入れ直す杯数（元のカードの杯数まで） */
      cups?: number;
      /** @description 抽出中の元のカードを途中でやめる */
      interrupt?: boolean;
      /** Format: double */
      queue_pos?: number | null;
      /** @description 操作の前の行（結果の changed と deleted のうち、操作の前からあったもの） */
      before?: components["schemas"]["CaosDrip"][];
      /** @description 操作が返した changed */
      after?: components["schemas"]["CaosDrip"][];
      /** @description 操作が準備完了にした注文（まだ提供していなければ取り消す） */
      readied?: string[];
    };
    CaosOpResult: {
      /** Format: date */
      day: string;
      /** Format: int64 */
      v: number;
      changed: components["schemas"]["CaosDrip"][];
      deleted: string[];
      /** @description この操作で準備完了にした注文 */
      readied: string[];
    };
    CaosErrorResponse: {
      /** @example ドリッパー 3 は抽出中ではありません */
      error: string;
      /** @enum {string} */
      code?: "invalid";
    };
    /**
     * @description WebSocket（/api/ws/orders）で届く CaOS のメッセージ（POS の画面は知らない type を無視する）。
     * drips：このインスタンスで変わったカード（drips は消えただけのときは省く）と消えたカード。
     * drips_version：ほかのインスタンスで盤面が変わった。手元の版より新しければ GET /api/caos/boards/{day} で読み直す。
     */
    CaosWSMessage: {
      /** @enum {string} */
      type: "drips" | "drips_version";
      /** Format: date */
      day: string;
      /** Format: int64 */
      v: number;
      drips?: components["schemas"]["CaosDrip"][];
      deleted?: string[];
    };
    ErrorResponse: {
      /** @example Invalid order ID format */
      error: string;
    };
    /** @enum {string} */
    StockResourceKind: "cup" | "bean";
    StockResourceRequest: {
      kind: components["schemas"]["StockResourceKind"];
      /** @example ホットカップ */
      name: string;
      /**
       * @description 数える単位（個 / g）
       * @example 個
       */
      unit: string;
      /**
       * Format: double
       * @description 1杯あたりの量。残量を杯数に換算するのに使う（カップ 1、豆 15）
       * @example 1
       */
      per_serving: number;
      /**
       * @description 残りがこの杯数を切ったら通知を始める
       * @example 500
       */
      notify_from: number;
      /**
       * @description notify_from から何杯減るごとに通知するか
       * @example 100
       */
      notify_step: number;
      /**
       * @description 最低限残したい杯数。これを切ると危険扱い
       * @example 100
       */
      buffer: number;
    };
    StockResourceResponse: components["schemas"]["StockResourceRequest"] & {
      /** Format: uuid */
      id: string;
    };
    /**
     * @description untracked は棚卸し・入荷がまだ一度も無い
     * @enum {string}
     */
    InventoryLevel: "ok" | "warning" | "critical" | "untracked";
    InventoryStatus: {
      resource: components["schemas"]["StockResourceResponse"];
      level: components["schemas"]["InventoryLevel"];
      /**
       * Format: date-time
       * @description 最後の棚卸し。無ければ最初の入荷
       */
      counted_at?: string | null;
      /** Format: double */
      counted_quantity?: number | null;
      /**
       * Format: double
       * @description counted_at 以降の入荷・調整の合計
       */
      received: number;
      /**
       * Format: double
       * @description counted_at 以降の注文での消費量
       */
      consumed: number;
      /** @description counted_at 以降に売れた杯数 */
      servings: number;
      /** Format: double */
      remaining?: number | null;
      /** Format: double */
      remaining_servings?: number | null;
      /** @description 直近1時間に売れた杯数 */
      servings_last_hour: number;
    };
    /** @enum {string} */
    StockEventKind: "count" | "receipt" | "adjust";
    StockEventCreateRequest: {
      kind: components["schemas"]["StockEventKind"];
      /** Format: double */
      quantity: number;
      note?: string;
    };
    StockEventResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      resource_id: string;
      kind: components["schemas"]["StockEventKind"];
      /** Format: double */
      quantity: number;
      note?: string;
      /** Format: date-time */
      created_at: string;
    };
    StockEventCreateResponse: {
      event: components["schemas"]["StockEventResponse"];
      /**
       * Format: double
       * @description 記録する直前の推定残量（count のときの答え合わせ用）
       */
      estimated?: number | null;
      /**
       * Format: double
       * @description 前回の棚卸しから今回までの実測の1杯あたり使用量（count のときだけ）
       */
      actual_per_serving?: number | null;
    };
    StockUsage: {
      /** Format: uuid */
      item_id: string;
      /** Format: uuid */
      resource_id: string;
      /**
       * Format: double
       * @description アイテム1杯で使う量（カップ 1、豆 15 など）
       */
      amount: number;
    };
    InventoryRemindResponse: {
      sent: boolean;
      reason?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** サーバーステータス取得 */
  getStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  /** アイテム一覧取得 */
  getItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"][];
        };
      };
    };
  };
  /** アイテム作成 */
  createItem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** idからアイテム情報取得 */
  getItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** アイテム情報更新 */
  updateItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** アイテム削除 */
  deleteItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** メニュー一覧取得 */
  getMenus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"][];
        };
      };
    };
  };
  /** メニュー作成 */
  createMenu: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MenuCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー取得 */
  getMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー更新 */
  updateMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MenuUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー削除 */
  deleteMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** アイテムタイプ一覧取得 */
  getItemTypes: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"][];
        };
      };
    };
  };
  /** アイテムタイプ作成 */
  createItemType: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemTypeCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** idからアイテムタイプ情報取得 */
  getItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** アイテム情報更新 */
  updateItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemTypeUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** アイテムタイプ削除 */
  deleteItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** 背景色設定一覧取得 */
  getColorSettings: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ColorSettingResponse"][];
        };
      };
    };
  };
  /**
   * 背景色設定の作成・更新
   * @description 対象（target_type, target_id）と画面（screen）の組が既にあれば色を上書きし、無ければ作成する
   */
  upsertColorSetting: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ColorSettingUpsertRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ColorSettingResponse"];
        };
      };
      /** @description リクエストが不正 */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** 背景色設定削除 */
  deleteColorSetting: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
      /** @description 背景色設定が見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダー一覧取得 */
  getOrders: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
    };
  };
  /** オーダー作成 */
  createOrder: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** idからオーダー情報取得 */
  getOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** オーダー情報更新 */
  updateOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** オーダー削除 */
  deleteOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** オーダーを準備完了にする */
  markOrderReady: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダーを提供完了にする */
  markOrderServe: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** 特定オーダーのコメント一覧取得 */
  getOrderComments: {
    parameters: {
      path: {
        /** @description オーダーID */
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CommentResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダーにコメント追加 */
  createOrderComment: {
    parameters: {
      path: {
        /** @description オーダーID */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreateRequest"];
      };
    };
    responses: {
      /** @description 作成成功 */
      201: {
        content: {
          "application/json": components["schemas"]["CommentResponse"];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * CaOS の盤面（その日の全カードと版）
   * @description 読む前に、その日の注文と照らし合わせてカードをそろえる。CaOS の画面は、つないだとき・
   * WebSocket の drips_version で手元より新しい版を知ったときに読み直す。
   */
  getCaosBoard: {
    parameters: {
      path: {
        /** @description 営業日（日本時間の日付） */
        day: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CaosBoard"];
        };
      };
      /** @description 日付の形が違う */
      422: {
        content: {
          "application/json": components["schemas"]["CaosErrorResponse"];
        };
      };
    };
  };
  /**
   * CaOS の盤面への操作
   * @description 割当・戻す・次へ・統合・入れ直し・1つ戻すのどれか 1 つ（name で選ぶ）。1 つの盤面への操作は 1 件ずつ順番に処理する。
   * 注文のカードが全部終わったら、同じトランザクションで注文を準備完了にする（readied）。
   * 変わったカードは WebSocket（/api/ws/orders）の drips でほかの画面にも届く。
   */
  applyCaosOp: {
    parameters: {
      path: {
        /** @description 営業日（日本時間の日付） */
        day: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaosOp"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CaosOpResult"];
        };
      };
      /** @description ルールに合わない操作（何も変えない）。error を画面にそのまま出す */
      422: {
        content: {
          "application/json": components["schemas"]["CaosErrorResponse"];
        };
      };
    };
  };
  /** マスターステート取得 */
  getMasterState: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MasterStateResponse"][];
        };
      };
    };
  };
  /** マスターステート更新 */
  updateMasterState: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterStateUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MasterStateResponse"];
        };
      };
    };
  };
  /**
   * 在庫の残量一覧
   * @description 最後の棚卸しからの入荷・注文での消費を差し引いた推定残量。
   */
  getInventory: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["InventoryStatus"][];
        };
      };
    };
  };
  /** 在庫対象の作成 */
  createStockResource: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockResourceRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["StockResourceResponse"];
        };
      };
    };
  };
  /** 在庫対象の更新 */
  updateStockResource: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockResourceRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StockResourceResponse"];
        };
      };
    };
  };
  /** 在庫対象の削除 */
  deleteStockResource: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /**
   * 棚卸し・入荷・調整の記録
   * @description count は実数で残量を置き換える（0 以上）。receipt は入荷として正の数を足す。adjust は差分として足す（減らすときは負の値、0 は不可）。
   */
  createStockEvent: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockEventCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["StockEventCreateResponse"];
        };
      };
    };
  };
  /** アイテム1杯あたりの使用量一覧 */
  getStockUsages: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StockUsage"][];
        };
      };
    };
  };
  /** アイテム1杯あたりの使用量をまとめて置き換える */
  replaceStockUsages: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockUsage"][];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StockUsage"][];
        };
      };
    };
  };
  /**
   * 残量確認のリマインドを Slack に送る
   * @description スケジューラから定期的に叩く。次のどちらかを満たさないと 401。
   *   - Authorization: Bearer の Google ID トークン（INVENTORY_REMIND_INVOKER の SA が audience INVENTORY_REMIND_AUDIENCE で発行したもの）。本番の Cloud Scheduler はこちら
   *   - X-Cron-Secret ヘッダーが INVENTORY_CRON_SECRET と一致する。ローカルや手動実行用
   * （ヘッダーをパラメータやセキュリティスキームとして書くと、生成される api_gin.go が models の型を参照できずビルドが通らないので説明だけに留める）
   * 直近に注文が無い（営業していない）ときは送らない。
   */
  remindInventory: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["InventoryRemindResponse"];
        };
      };
      /** @description ID トークンも合言葉も合わない */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
