/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    /** サーバーステータス取得 */
    get: operations["getStatus"];
  };
  "/api/items": {
    /** アイテム一覧取得 */
    get: operations["getItems"];
    /** アイテム作成 */
    post: operations["createItem"];
  };
  "/api/items/{id}": {
    /** idからアイテム情報取得 */
    get: operations["getItem"];
    /** アイテム情報更新 */
    put: operations["updateItem"];
    /** アイテム削除 */
    delete: operations["deleteItem"];
  };
  "/api/menus": {
    /** メニュー一覧取得 */
    get: operations["getMenus"];
    /** メニュー作成 */
    post: operations["createMenu"];
  };
  "/api/menus/{id}": {
    /** メニュー取得 */
    get: operations["getMenu"];
    /** メニュー更新 */
    put: operations["updateMenu"];
    /** メニュー削除 */
    delete: operations["deleteMenu"];
  };
  "/api/item-types": {
    /** アイテムタイプ一覧取得 */
    get: operations["getItemTypes"];
    /** アイテムタイプ作成 */
    post: operations["createItemType"];
  };
  "/api/item-types/{id}": {
    /** idからアイテムタイプ情報取得 */
    get: operations["getItemType"];
    /** アイテム情報更新 */
    put: operations["updateItemType"];
    /** アイテムタイプ削除 */
    delete: operations["deleteItemType"];
  };
  "/api/orders": {
    /** オーダー一覧取得 */
    get: operations["getOrders"];
    /** オーダー作成 */
    post: operations["createOrder"];
  };
  "/api/orders/{id}": {
    /** idからオーダー情報取得 */
    get: operations["getOrder"];
    /** オーダー情報更新 */
    put: operations["updateOrder"];
    /** オーダー削除 */
    delete: operations["deleteOrder"];
  };
  "/api/orders/{id}/ready": {
    /** オーダーを準備完了にする */
    patch: operations["markOrderReady"];
  };
  "/api/orders/{id}/served": {
    /** オーダーを提供完了にする */
    patch: operations["markOrderServe"];
  };
  "/api/orders/{id}/comments": {
    /** 特定オーダーのコメント一覧取得 */
    get: operations["getOrderComments"];
    /** オーダーにコメント追加 */
    post: operations["createOrderComment"];
  };
  "/api/master-status": {
    /** マスターステート取得 */
    get: operations["getMasterState"];
    /** マスターステート更新 */
    post: operations["updateMasterState"];
  };
  "/api/cashier-state": {
    /**
     * レジ状態取得
     * @description レジが編集中の注文と直前に確定した注文の ID。まだ一度も同期されていなければ 404。
     */
    get: operations["getCashierState"];
    /**
     * レジ状態更新
     * @description 単一のレジ状態を丸ごと置き換える。成功すると WebSocket で全クライアントへ配信される。
     */
    put: operations["updateCashierState"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StatusResponse: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
      /** @example 1.0.0 */
      version: string;
      /** @example connected */
      database: string;
    };
    ItemResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      item_type: components["schemas"]["ItemTypeResponse"];
    };
    ItemCreateRequest: {
      name: string;
      abbr: string;
      /** Format: uuid */
      item_type_id: string;
    };
    ItemUpdateRequest: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      /** Format: uuid */
      item_type_id: string;
    };
    MenuItemResponse: {
      item: components["schemas"]["ItemResponse"];
      quantity: number;
    };
    MenuItemRequest: {
      /** Format: uuid */
      item_id: string;
      quantity: number;
    };
    MenuResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      price: number;
      key: string;
      items: components["schemas"]["MenuItemResponse"][];
    };
    MenuCreateRequest: {
      name: string;
      abbr: string;
      price: number;
      key: string;
      items: components["schemas"]["MenuItemRequest"][];
    };
    MenuUpdateRequest: components["schemas"]["MenuCreateRequest"] & {
      /** Format: uuid */
      id: string;
    };
    ItemTypeResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
    };
    ItemTypeCreateRequest: {
      name: string;
      display_name: string;
    };
    ItemTypeUpdateRequest: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
    };
    MenuInfo: {
      /**
       * Format: uuid
       * @description 注文明細ID
       */
      id: string;
      /** @description 注文時点のメニュー名 */
      menu_name: string;
      /** @description 注文時点のメニュー価格 */
      unit_price: number;
      menu: components["schemas"]["MenuResponse"];
      assignee: string | null;
    };
    MenuInfoCreate: {
      /**
       * Format: uuid
       * @description 更新時に残す既存明細のID。新規明細では省略する。価格・名称はサーバーが保存する。
       */
      order_menu_id?: string;
      /** Format: uuid */
      menu_id: string;
      assignee: string | null;
    };
    OrderResponse: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received: number;
      discount_order_id?: number | null;
      discount_order_cups?: number;
      menus: components["schemas"]["MenuInfo"][];
      comments?: components["schemas"]["CommentResponse"][];
    };
    OrderCreateRequest: {
      /** @example 1 */
      order_id: number;
      /** @example 500 */
      billing_amount: number;
      /**
       * @default 0
       * @example 500
       */
      received: number;
      discount_order_id?: number | null;
      /** @default 0 */
      discount_order_cups?: number;
      menu_ids: components["schemas"]["MenuInfoCreate"][];
      comments?: components["schemas"]["CommentCreateRequest"][];
    };
    OrderUpdateRequest: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received: number;
      discount_order_id?: number | null;
      discount_order_cups?: number;
      menu_ids: components["schemas"]["MenuInfoCreate"][];
    };
    OrderListItem: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received?: number;
      discount_order_cups?: number;
    };
    CommentCreateRequest: {
      author: string;
      text: string;
    };
    CommentResponse: {
      /** Format: uuid */
      order_id: string;
      author: string;
      text: string;
      /** Format: date-time */
      created_at: string;
    };
    MasterStateResponse: {
      /** Format: date-time */
      created_at: string;
      type: string;
    };
    MasterStateUpdateRequest: {
      type: string;
    };
    CashierStateResponse: {
      /** @description レジで編集中の注文。フロントの orderSchema の JSON をそのまま保持し、サーバーは中身を解釈しない */
      editting_order: {
        [key: string]: unknown;
      };
      /**
       * Format: uuid
       * @description 直前に確定した注文の ID。編集中は null
       */
      submitted_order_id: string | null;
      /** Format: date-time */
      updated_at: string;
    };
    CashierStateUpdateRequest: {
      editting_order: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      submitted_order_id: string | null;
    };
    ErrorResponse: {
      /** @example Invalid order ID format */
      error: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** サーバーステータス取得 */
  getStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  /** アイテム一覧取得 */
  getItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"][];
        };
      };
    };
  };
  /** アイテム作成 */
  createItem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** idからアイテム情報取得 */
  getItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** アイテム情報更新 */
  updateItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** アイテム削除 */
  deleteItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** メニュー一覧取得 */
  getMenus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"][];
        };
      };
    };
  };
  /** メニュー作成 */
  createMenu: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MenuCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー取得 */
  getMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー更新 */
  updateMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MenuUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー削除 */
  deleteMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** アイテムタイプ一覧取得 */
  getItemTypes: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"][];
        };
      };
    };
  };
  /** アイテムタイプ作成 */
  createItemType: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemTypeCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** idからアイテムタイプ情報取得 */
  getItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** アイテム情報更新 */
  updateItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemTypeUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** アイテムタイプ削除 */
  deleteItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** オーダー一覧取得 */
  getOrders: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
    };
  };
  /** オーダー作成 */
  createOrder: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** idからオーダー情報取得 */
  getOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** オーダー情報更新 */
  updateOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** オーダー削除 */
  deleteOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** オーダーを準備完了にする */
  markOrderReady: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダーを提供完了にする */
  markOrderServe: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** 特定オーダーのコメント一覧取得 */
  getOrderComments: {
    parameters: {
      path: {
        /** @description オーダーID */
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CommentResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダーにコメント追加 */
  createOrderComment: {
    parameters: {
      path: {
        /** @description オーダーID */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreateRequest"];
      };
    };
    responses: {
      /** @description 作成成功 */
      201: {
        content: {
          "application/json": components["schemas"]["CommentResponse"];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** マスターステート取得 */
  getMasterState: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MasterStateResponse"][];
        };
      };
    };
  };
  /** マスターステート更新 */
  updateMasterState: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterStateUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MasterStateResponse"];
        };
      };
    };
  };
  /**
   * レジ状態取得
   * @description レジが編集中の注文と直前に確定した注文の ID。まだ一度も同期されていなければ 404。
   */
  getCashierState: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CashierStateResponse"];
        };
      };
      /** @description まだレジ状態が無い */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * レジ状態更新
   * @description 単一のレジ状態を丸ごと置き換える。成功すると WebSocket で全クライアントへ配信される。
   */
  updateCashierState: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CashierStateUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CashierStateResponse"];
        };
      };
    };
  };
}
