/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    /** サーバーステータス取得 */
    get: operations["getStatus"];
  };
  "/api/items": {
    /** アイテム一覧取得 */
    get: operations["getItems"];
    /** アイテム作成 */
    post: operations["createItem"];
  };
  "/api/items/{id}": {
    /** idからアイテム情報取得 */
    get: operations["getItem"];
    /** アイテム情報更新 */
    put: operations["updateItem"];
    /** アイテム削除 */
    delete: operations["deleteItem"];
  };
  "/api/menus": {
    /** メニュー一覧取得 */
    get: operations["getMenus"];
    /** メニュー作成 */
    post: operations["createMenu"];
  };
  "/api/menus/{id}": {
    /** メニュー取得 */
    get: operations["getMenu"];
    /** メニュー更新 */
    put: operations["updateMenu"];
    /** メニュー削除 */
    delete: operations["deleteMenu"];
  };
  "/api/item-types": {
    /** アイテムタイプ一覧取得 */
    get: operations["getItemTypes"];
    /** アイテムタイプ作成 */
    post: operations["createItemType"];
  };
  "/api/item-types/{id}": {
    /** idからアイテムタイプ情報取得 */
    get: operations["getItemType"];
    /** アイテム情報更新 */
    put: operations["updateItemType"];
    /** アイテムタイプ削除 */
    delete: operations["deleteItemType"];
  };
  "/api/color-settings": {
    /** 背景色設定一覧取得 */
    get: operations["getColorSettings"];
    /**
     * 背景色設定の作成・更新
     * @description 対象（target_type, target_id）と画面（screen）の組が既にあれば色を上書きし、無ければ作成する
     */
    put: operations["upsertColorSetting"];
  };
  "/api/color-settings/{id}": {
    /** 背景色設定削除 */
    delete: operations["deleteColorSetting"];
  };
  "/api/orders": {
    /** オーダー一覧取得 */
    get: operations["getOrders"];
    /** オーダー作成 */
    post: operations["createOrder"];
  };
  "/api/orders/{id}": {
    /** idからオーダー情報取得 */
    get: operations["getOrder"];
    /** オーダー情報更新 */
    put: operations["updateOrder"];
    /** オーダー削除 */
    delete: operations["deleteOrder"];
  };
  "/api/orders/{id}/ready": {
    /** オーダーを準備完了にする */
    patch: operations["markOrderReady"];
  };
  "/api/orders/{id}/served": {
    /** オーダーを提供完了にする */
    patch: operations["markOrderServe"];
  };
  "/api/orders/{id}/comments": {
    /** 特定オーダーのコメント一覧取得 */
    get: operations["getOrderComments"];
    /** オーダーにコメント追加 */
    post: operations["createOrderComment"];
  };
  "/api/master-status": {
    /** マスターステート取得 */
    get: operations["getMasterState"];
    /** マスターステート更新 */
    post: operations["updateMasterState"];
  };
  "/api/inventory": {
    /**
     * 在庫の残量一覧
     * @description 最後の棚卸しからの入荷・注文での消費を差し引いた推定残量。
     */
    get: operations["getInventory"];
  };
  "/api/inventory/resources": {
    /** 在庫対象の作成 */
    post: operations["createStockResource"];
  };
  "/api/inventory/resources/{id}": {
    /** 在庫対象の更新 */
    put: operations["updateStockResource"];
    /** 在庫対象の削除 */
    delete: operations["deleteStockResource"];
  };
  "/api/inventory/resources/{id}/events": {
    /**
     * 棚卸し・入荷・調整の記録
     * @description count は実数で残量を置き換える（0 以上）。receipt は入荷として正の数を足す。adjust は差分として足す（減らすときは負の値、0 は不可）。
     */
    post: operations["createStockEvent"];
  };
  "/api/inventory/usages": {
    /** アイテム1杯あたりの使用量一覧 */
    get: operations["getStockUsages"];
    /** アイテム1杯あたりの使用量をまとめて置き換える */
    put: operations["replaceStockUsages"];
  };
  "/api/inventory/remind": {
    /**
     * 残量確認のリマインドを Slack に送る
     * @description スケジューラから定期的に叩く。次のどちらかを満たさないと 401。
     *   - Authorization: Bearer の Google ID トークン（INVENTORY_REMIND_INVOKER の SA が audience INVENTORY_REMIND_AUDIENCE で発行したもの）。本番の Cloud Scheduler はこちら
     *   - X-Cron-Secret ヘッダーが INVENTORY_CRON_SECRET と一致する。ローカルや手動実行用
     * （ヘッダーをパラメータやセキュリティスキームとして書くと、生成される api_gin.go が models の型を参照できずビルドが通らないので説明だけに留める）
     * 直近に注文が無い（営業していない）ときは送らない。
     */
    post: operations["remindInventory"];
  };
  "/api/square/status": {
    /**
     * Square 連携が使えるか
     * @description SQUARE_ACCESS_TOKEN と SQUARE_DEVICE_ID が揃っていれば enabled。フロントはこれを見て Square の決済ボタンを出す。
     */
    get: operations["getSquareStatus"];
  };
  "/api/square/checkouts": {
    /**
     * Square Terminal に決済画面を出す
     * @description 決済が先・注文が後の順で使う。完了したら、返ってきた id を square_checkout_id に入れて POST /api/orders する。
     * 同じ idempotency_key で再送したときは、新しく作らずに同じ決済依頼を返す。
     * 別の決済依頼が進行中なら 409 を返し、進行中のものを checkout に入れる。
     */
    post: operations["createSquareCheckout"];
  };
  "/api/square/checkouts/unlinked": {
    /**
     * 支払い済みなのに注文と結び付いていない決済依頼
     * @description 決済中にレジが落ちた・注文の送信に失敗したなどで、お金だけ受け取った状態のものを照合するために使う。新しい順。
     */
    get: operations["getUnlinkedSquareCheckouts"];
  };
  "/api/square/checkouts/{id}": {
    /**
     * 決済依頼の状態を取る
     * @description 未確定なら Square に問い合わせて最新にしてから返す。レジはこれを数秒おきに呼んで完了を待つ。
     */
    get: operations["getSquareCheckout"];
  };
  "/api/square/checkouts/{id}/cancel": {
    /**
     * 決済依頼を取り消す
     * @description PENDING / IN_PROGRESS のときだけ取り消せる。電子マネーで端末にエラーが出ているときは API から取り消せないので、端末側で取り消す。
     */
    post: operations["cancelSquareCheckout"];
  };
  "/api/square/webhook": {
    /**
     * Square からの Webhook（terminal.checkout.created / terminal.checkout.updated）
     * @description x-square-hmacsha256-signature ヘッダーの署名が合わなければ 403。
     * （ヘッダーをパラメータとして書くと、生成される api_gin.go が models の型を参照できずビルドが通らないので説明だけに留める）
     */
    post: operations["receiveSquareWebhook"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StatusResponse: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
      /** @example 1.0.0 */
      version: string;
      /** @example connected */
      database: string;
    };
    ItemResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      item_type: components["schemas"]["ItemTypeResponse"];
    };
    ItemCreateRequest: {
      name: string;
      abbr: string;
      /** Format: uuid */
      item_type_id: string;
    };
    ItemUpdateRequest: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      /** Format: uuid */
      item_type_id: string;
    };
    MenuItemResponse: {
      item: components["schemas"]["ItemResponse"];
      quantity: number;
    };
    MenuItemRequest: {
      /** Format: uuid */
      item_id: string;
      quantity: number;
    };
    MenuResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      abbr: string;
      price: number;
      key: string;
      items: components["schemas"]["MenuItemResponse"][];
    };
    MenuCreateRequest: {
      name: string;
      abbr: string;
      price: number;
      key: string;
      items: components["schemas"]["MenuItemRequest"][];
    };
    MenuUpdateRequest: components["schemas"]["MenuCreateRequest"] & {
      /** Format: uuid */
      id: string;
    };
    ItemTypeResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
    };
    ItemTypeCreateRequest: {
      name: string;
      display_name: string;
    };
    ItemTypeUpdateRequest: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
    };
    MenuInfo: {
      /**
       * Format: uuid
       * @description 注文明細ID
       */
      id: string;
      /** @description 注文時点のメニュー名 */
      menu_name: string;
      /** @description 注文時点のメニュー価格 */
      unit_price: number;
      menu: components["schemas"]["MenuResponse"];
      assignee: string | null;
    };
    MenuInfoCreate: {
      /**
       * Format: uuid
       * @description 更新時に残す既存明細のID。新規明細では省略する。価格・名称はサーバーが保存する。
       */
      order_menu_id?: string;
      /** Format: uuid */
      menu_id: string;
      assignee: string | null;
    };
    OrderResponse: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received: number;
      discount_order_id?: number | null;
      discount_order_cups?: number;
      payment_method: components["schemas"]["PaymentMethod"];
      menus: components["schemas"]["MenuInfo"][];
      comments?: components["schemas"]["CommentResponse"][];
    };
    OrderCreateRequest: {
      /** @example 1 */
      order_id: number;
      /** @example 500 */
      billing_amount: number;
      /**
       * @default 0
       * @example 500
       */
      received: number;
      discount_order_id?: number | null;
      /** @default 0 */
      discount_order_cups?: number;
      payment_method?: components["schemas"]["PaymentMethod"];
      /**
       * Format: uuid
       * @description payment_method が square のとき必須。COMPLETED で金額が billing_amount と一致し、まだどの注文にも使われていない決済依頼の id。
       */
      square_checkout_id?: string | null;
      menu_ids: components["schemas"]["MenuInfoCreate"][];
      comments?: components["schemas"]["CommentCreateRequest"][];
    };
    OrderUpdateRequest: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received: number;
      discount_order_id?: number | null;
      discount_order_cups?: number;
      menu_ids: components["schemas"]["MenuInfoCreate"][];
    };
    OrderListItem: {
      /** Format: uuid */
      id: string;
      order_id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at?: string | null;
      /** Format: date-time */
      served_at?: string | null;
      billing_amount: number;
      received?: number;
      discount_order_cups?: number;
    };
    CommentCreateRequest: {
      author: string;
      text: string;
    };
    CommentResponse: {
      /** Format: uuid */
      order_id: string;
      author: string;
      text: string;
      /** Format: date-time */
      created_at: string;
    };
    MasterStateResponse: {
      /** Format: date-time */
      created_at: string;
      type: string;
    };
    MasterStateUpdateRequest: {
      type: string;
    };
    /**
     * @description 背景色を設定する対象の種類
     * @enum {string}
     */
    ColorTargetType: "Item" | "ItemType";
    /**
     * @description 背景色を適用する画面
     * @enum {string}
     */
    ColorScreen: "master" | "serve";
    ColorSettingResponse: {
      /** Format: uuid */
      id: string;
      target_type: components["schemas"]["ColorTargetType"];
      /**
       * Format: uuid
       * @description Item または ItemType の ID
       */
      target_id: string;
      screen: components["schemas"]["ColorScreen"];
      /** @example #bfdbfe */
      color: string;
    };
    ColorSettingUpsertRequest: {
      target_type: components["schemas"]["ColorTargetType"];
      /**
       * Format: uuid
       * @description Item または ItemType の ID
       */
      target_id: string;
      screen: components["schemas"]["ColorScreen"];
      /** @example #bfdbfe */
      color: string;
    };
    ErrorResponse: {
      /** @example Invalid order ID format */
      error: string;
    };
    /** @enum {string} */
    StockResourceKind: "cup" | "bean";
    StockResourceRequest: {
      kind: components["schemas"]["StockResourceKind"];
      /** @example ホットカップ */
      name: string;
      /**
       * @description 数える単位（個 / g）
       * @example 個
       */
      unit: string;
      /**
       * Format: double
       * @description 1杯あたりの量。残量を杯数に換算するのに使う（カップ 1、豆 15）
       * @example 1
       */
      per_serving: number;
      /**
       * @description 残りがこの杯数を切ったら通知を始める
       * @example 500
       */
      notify_from: number;
      /**
       * @description notify_from から何杯減るごとに通知するか
       * @example 100
       */
      notify_step: number;
      /**
       * @description 最低限残したい杯数。これを切ると危険扱い
       * @example 100
       */
      buffer: number;
    };
    StockResourceResponse: components["schemas"]["StockResourceRequest"] & {
      /** Format: uuid */
      id: string;
    };
    /**
     * @description untracked は棚卸し・入荷がまだ一度も無い
     * @enum {string}
     */
    InventoryLevel: "ok" | "warning" | "critical" | "untracked";
    InventoryStatus: {
      resource: components["schemas"]["StockResourceResponse"];
      level: components["schemas"]["InventoryLevel"];
      /**
       * Format: date-time
       * @description 最後の棚卸し。無ければ最初の入荷
       */
      counted_at?: string | null;
      /** Format: double */
      counted_quantity?: number | null;
      /**
       * Format: double
       * @description counted_at 以降の入荷・調整の合計
       */
      received: number;
      /**
       * Format: double
       * @description counted_at 以降の注文での消費量
       */
      consumed: number;
      /** @description counted_at 以降に売れた杯数 */
      servings: number;
      /** Format: double */
      remaining?: number | null;
      /** Format: double */
      remaining_servings?: number | null;
      /** @description 直近1時間に売れた杯数 */
      servings_last_hour: number;
    };
    /** @enum {string} */
    StockEventKind: "count" | "receipt" | "adjust";
    StockEventCreateRequest: {
      kind: components["schemas"]["StockEventKind"];
      /** Format: double */
      quantity: number;
      note?: string;
    };
    StockEventResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      resource_id: string;
      kind: components["schemas"]["StockEventKind"];
      /** Format: double */
      quantity: number;
      note?: string;
      /** Format: date-time */
      created_at: string;
    };
    StockEventCreateResponse: {
      event: components["schemas"]["StockEventResponse"];
      /**
       * Format: double
       * @description 記録する直前の推定残量（count のときの答え合わせ用）
       */
      estimated?: number | null;
      /**
       * Format: double
       * @description 前回の棚卸しから今回までの実測の1杯あたり使用量（count のときだけ）
       */
      actual_per_serving?: number | null;
    };
    StockUsage: {
      /** Format: uuid */
      item_id: string;
      /** Format: uuid */
      resource_id: string;
      /**
       * Format: double
       * @description アイテム1杯で使う量（カップ 1、豆 15 など）
       */
      amount: number;
    };
    InventoryRemindResponse: {
      sent: boolean;
      reason?: string;
    };
    /**
     * @description 支払い方法。square は Square Terminal での決済（カード・電子マネー・QR）
     * @default cash
     * @enum {string}
     */
    PaymentMethod: "cash" | "square";
    /**
     * @description Square Terminal に出す決済画面の種類（Square の payment_type をそのまま使う）
     * @enum {string}
     */
    SquarePaymentType: "CARD_PRESENT" | "FELICA_ALL" | "QR_CODE";
    /**
     * @description レジが次に何をすべきかをサーバーが判定したもの。
     *   - pending: まだ決まっていない。待つ
     *   - paid: 支払い済みで、受取額も依頼額と一致した。注文を送ってよい
     *   - failed: 取り消された・失敗した。お金は受け取っていない
     *   - attention: 完了したが受取額が依頼額と合わないなど、人が Square の管理画面で確かめる必要がある
     *
     * @enum {string}
     */
    SquareCheckoutOutcome: "pending" | "paid" | "failed" | "attention";
    SquareStatusResponse: {
      enabled: boolean;
      /** @description production か sandbox */
      environment: string;
      webhook_enabled: boolean;
    };
    SquareCheckoutCreateRequest: {
      /** @description レジが決済ごとに作る一意な値（UUID）。再送しても二重に決済画面が出ないようにする */
      idempotency_key: string;
      /** @description 請求額（円） */
      amount: number;
      payment_type: components["schemas"]["SquarePaymentType"];
      /** @description 依頼時点の注文番号（端末のメモと照合の表示に使う） */
      order_number?: number | null;
    };
    SquareCheckoutResponse: {
      /** Format: uuid */
      id: string;
      /** @description Square の TerminalCheckout の id */
      checkout_id?: string | null;
      /** @description Square の status（PENDING / IN_PROGRESS / CANCEL_REQUESTED / CANCELED / COMPLETED）。依頼前は CREATING、依頼に失敗したら ERROR */
      status: string;
      outcome: components["schemas"]["SquareCheckoutOutcome"];
      cancel_reason?: string | null;
      amount: number;
      /** @description 完了後に Payments API で確かめた受取額（円） */
      paid_amount?: number | null;
      payment_type: string;
      payment_ids: string[];
      error_message?: string | null;
      order_number?: number | null;
      /**
       * Format: uuid
       * @description この決済で作った注文。まだ無ければ null
       */
      order_id?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    SquareCheckoutConflictResponse: {
      error: string;
      checkout: components["schemas"]["SquareCheckoutResponse"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** サーバーステータス取得 */
  getStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  /** アイテム一覧取得 */
  getItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"][];
        };
      };
    };
  };
  /** アイテム作成 */
  createItem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** idからアイテム情報取得 */
  getItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** アイテム情報更新 */
  updateItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemResponse"];
        };
      };
    };
  };
  /** アイテム削除 */
  deleteItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** メニュー一覧取得 */
  getMenus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"][];
        };
      };
    };
  };
  /** メニュー作成 */
  createMenu: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MenuCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー取得 */
  getMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー更新 */
  updateMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MenuUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuResponse"];
        };
      };
    };
  };
  /** メニュー削除 */
  deleteMenu: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** アイテムタイプ一覧取得 */
  getItemTypes: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"][];
        };
      };
    };
  };
  /** アイテムタイプ作成 */
  createItemType: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemTypeCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** idからアイテムタイプ情報取得 */
  getItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** アイテム情報更新 */
  updateItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemTypeUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ItemTypeResponse"];
        };
      };
    };
  };
  /** アイテムタイプ削除 */
  deleteItemType: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** 背景色設定一覧取得 */
  getColorSettings: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ColorSettingResponse"][];
        };
      };
    };
  };
  /**
   * 背景色設定の作成・更新
   * @description 対象（target_type, target_id）と画面（screen）の組が既にあれば色を上書きし、無ければ作成する
   */
  upsertColorSetting: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ColorSettingUpsertRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ColorSettingResponse"];
        };
      };
      /** @description リクエストが不正 */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** 背景色設定削除 */
  deleteColorSetting: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
      /** @description 背景色設定が見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダー一覧取得 */
  getOrders: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
    };
  };
  /** オーダー作成 */
  createOrder: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** idからオーダー情報取得 */
  getOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** オーダー情報更新 */
  updateOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"];
        };
      };
    };
  };
  /** オーダー削除 */
  deleteOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /** オーダーを準備完了にする */
  markOrderReady: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダーを提供完了にする */
  markOrderServe: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** 特定オーダーのコメント一覧取得 */
  getOrderComments: {
    parameters: {
      path: {
        /** @description オーダーID */
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CommentResponse"][];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** オーダーにコメント追加 */
  createOrderComment: {
    parameters: {
      path: {
        /** @description オーダーID */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreateRequest"];
      };
    };
    responses: {
      /** @description 作成成功 */
      201: {
        content: {
          "application/json": components["schemas"]["CommentResponse"];
        };
      };
      /** @description オーダーが見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** マスターステート取得 */
  getMasterState: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MasterStateResponse"][];
        };
      };
    };
  };
  /** マスターステート更新 */
  updateMasterState: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterStateUpdateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MasterStateResponse"];
        };
      };
    };
  };
  /**
   * 在庫の残量一覧
   * @description 最後の棚卸しからの入荷・注文での消費を差し引いた推定残量。
   */
  getInventory: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["InventoryStatus"][];
        };
      };
    };
  };
  /** 在庫対象の作成 */
  createStockResource: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockResourceRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["StockResourceResponse"];
        };
      };
    };
  };
  /** 在庫対象の更新 */
  updateStockResource: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockResourceRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StockResourceResponse"];
        };
      };
    };
  };
  /** 在庫対象の削除 */
  deleteStockResource: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
    };
  };
  /**
   * 棚卸し・入荷・調整の記録
   * @description count は実数で残量を置き換える（0 以上）。receipt は入荷として正の数を足す。adjust は差分として足す（減らすときは負の値、0 は不可）。
   */
  createStockEvent: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockEventCreateRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["StockEventCreateResponse"];
        };
      };
    };
  };
  /** アイテム1杯あたりの使用量一覧 */
  getStockUsages: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StockUsage"][];
        };
      };
    };
  };
  /** アイテム1杯あたりの使用量をまとめて置き換える */
  replaceStockUsages: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockUsage"][];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StockUsage"][];
        };
      };
    };
  };
  /**
   * 残量確認のリマインドを Slack に送る
   * @description スケジューラから定期的に叩く。次のどちらかを満たさないと 401。
   *   - Authorization: Bearer の Google ID トークン（INVENTORY_REMIND_INVOKER の SA が audience INVENTORY_REMIND_AUDIENCE で発行したもの）。本番の Cloud Scheduler はこちら
   *   - X-Cron-Secret ヘッダーが INVENTORY_CRON_SECRET と一致する。ローカルや手動実行用
   * （ヘッダーをパラメータやセキュリティスキームとして書くと、生成される api_gin.go が models の型を参照できずビルドが通らないので説明だけに留める）
   * 直近に注文が無い（営業していない）ときは送らない。
   */
  remindInventory: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["InventoryRemindResponse"];
        };
      };
      /** @description ID トークンも合言葉も合わない */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Square 連携が使えるか
   * @description SQUARE_ACCESS_TOKEN と SQUARE_DEVICE_ID が揃っていれば enabled。フロントはこれを見て Square の決済ボタンを出す。
   */
  getSquareStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SquareStatusResponse"];
        };
      };
    };
  };
  /**
   * Square Terminal に決済画面を出す
   * @description 決済が先・注文が後の順で使う。完了したら、返ってきた id を square_checkout_id に入れて POST /api/orders する。
   * 同じ idempotency_key で再送したときは、新しく作らずに同じ決済依頼を返す。
   * 別の決済依頼が進行中なら 409 を返し、進行中のものを checkout に入れる。
   */
  createSquareCheckout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SquareCheckoutCreateRequest"];
      };
    };
    responses: {
      /** @description 同じ idempotency_key の決済依頼が既にある */
      200: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutResponse"];
        };
      };
      /** @description 作成した */
      201: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutResponse"];
        };
      };
      /** @description 入力が不正 */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 別の決済依頼が進行中 */
      409: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutConflictResponse"];
        };
      };
      /** @description Square が依頼を受け付けなかった */
      502: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutResponse"];
        };
      };
      /** @description Square 連携が設定されていない */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 支払い済みなのに注文と結び付いていない決済依頼
   * @description 決済中にレジが落ちた・注文の送信に失敗したなどで、お金だけ受け取った状態のものを照合するために使う。新しい順。
   */
  getUnlinkedSquareCheckouts: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutResponse"][];
        };
      };
    };
  };
  /**
   * 決済依頼の状態を取る
   * @description 未確定なら Square に問い合わせて最新にしてから返す。レジはこれを数秒おきに呼んで完了を待つ。
   */
  getSquareCheckout: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutResponse"];
        };
      };
      /** @description 見つからない */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 決済依頼を取り消す
   * @description PENDING / IN_PROGRESS のときだけ取り消せる。電子マネーで端末にエラーが出ているときは API から取り消せないので、端末側で取り消す。
   */
  cancelSquareCheckout: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 取り消しを依頼した（IN_PROGRESS だったときは CANCEL_REQUESTED を経て CANCELED になる） */
      200: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutResponse"];
        };
      };
      /** @description 見つからない */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Square が取り消しを受け付けなかった（既に完了しているなど） */
      409: {
        content: {
          "application/json": components["schemas"]["SquareCheckoutConflictResponse"];
        };
      };
    };
  };
  /**
   * Square からの Webhook（terminal.checkout.created / terminal.checkout.updated）
   * @description x-square-hmacsha256-signature ヘッダーの署名が合わなければ 403。
   * （ヘッダーをパラメータとして書くと、生成される api_gin.go が models の型を参照できずビルドが通らないので説明だけに留める）
   */
  receiveSquareWebhook: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description 受け取った */
      200: {
        content: never;
      };
      /** @description 署名が合わない */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Webhook の署名鍵が設定されていない */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
