/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    /** サーバーステータス取得 */
    get: operations["getStatus"];
  };
  "/api/items": {
    /** アイテム一覧取得 */
    get: operations["getItems"];
  };
  "/api/menu-items": {
    /** メニューアイテム一覧取得 */
    get: operations["getMenuItems"];
  };
  "/api/orders": {
    /** 注文一覧取得 */
    get: operations["getOrders"];
  };
  "/api/work-items": {
    /** 作業アイテム一覧取得 */
    get: operations["getWorkItems"];
  };
  "/api/work-items/{id}/status": {
    /** 作業アイテムのステータス更新 */
    put: operations["updateWorkItemStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StatusResponse: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
      /** @example 1.0.0 */
      version: string;
      /** @example connected */
      database: string;
    };
    Item: {
      /** Format: uuid */
      id: string;
      name: string;
      item_type: components["schemas"]["ItemType"];
    };
    /** @enum {string} */
    ItemType: "hot" | "ice" | "ore" | "milk" | "goods" | "other";
    MenuItem: {
      /** Format: uuid */
      id: string;
      name: string;
      price: number;
    };
    Order: {
      /** Format: uuid */
      id: string;
      order_num: number;
      /** Format: date-time */
      created_at: string;
    };
    OrderWorkItem: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      order_menu_item_id: string;
      /** Format: uuid */
      item_id: string;
      status: components["schemas"]["WorkItemStatus"];
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    WorkItemStatus: "pending" | "preparing" | "ready" | "served";
    UpdateStatusRequest: {
      status: components["schemas"]["WorkItemStatus"];
    };
    MessageResponse: {
      message: string;
    };
    ErrorResponse: {
      error: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** サーバーステータス取得 */
  getStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  /** アイテム一覧取得 */
  getItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Item"][];
        };
      };
    };
  };
  /** メニューアイテム一覧取得 */
  getMenuItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MenuItem"][];
        };
      };
    };
  };
  /** 注文一覧取得 */
  getOrders: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Order"][];
        };
      };
    };
  };
  /** 作業アイテム一覧取得 */
  getWorkItems: {
    parameters: {
      query?: {
        status?: components["schemas"]["WorkItemStatus"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OrderWorkItem"][];
        };
      };
    };
  };
  /** 作業アイテムのステータス更新 */
  updateWorkItemStatus: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateStatusRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description 見つかりません */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
