/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    /** サーバーステータス取得 */
    get: operations["getStatus"];
  };
  "/api/items": {
    /** アイテム一覧取得 */
    get: operations["getItems"];
  };
  "/api/menu-items": {
    /** メニューアイテム一覧取得 */
    get: operations["getMenuItems"];
  };
  "/api/orders": {
    /** 注文一覧取得 */
    get: operations["getOrders"];
  };
  "/api/work-items": {
    /** 作業アイテム一覧取得 */
    get: operations["getWorkItems"];
  };
  "/api/work-items/{id}/status": {
    /** 作業アイテムのステータス更新 */
    put: operations["updateWorkItemStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StatusResponse: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
      /** @example 1.0.0 */
      version: string;
      /** @example connected */
      database: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** サーバーステータス取得 */
  getStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  /** アイテム一覧取得 */
  getItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** メニューアイテム一覧取得 */
  getMenuItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** 注文一覧取得 */
  getOrders: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** 作業アイテム一覧取得 */
  getWorkItems: {
    parameters: {
      query?: {
        status?: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** 作業アイテムのステータス更新 */
  updateWorkItemStatus: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          status: string;
        };
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": {
            message?: string;
          };
        };
      };
      /** @description 見つかりません */
      404: {
        content: {
          "application/json": {
            error?: string;
          };
        };
      };
    };
  };
}
