/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    /** サーバーステータス取得 */
    get: operations["getStatus"];
  };
  "/api/items": {
    /** アイテム一覧取得 */
    get: operations["getItems"];
    /** アイテム作成 */
    post: operations["createItem"];
  };
  "/api/items/{id}": {
    /** idからアイテム情報取得 */
    get: operations["getItem"];
  };
  "/api/item-types": {
    /** タイプ一覧取得 */
    get: operations["getItemTypes"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StatusResponse: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
      /** @example 1.0.0 */
      version: string;
      /** @example connected */
      database: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** サーバーステータス取得 */
  getStatus: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  /** アイテム一覧取得 */
  getItems: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** アイテム作成 */
  createItem: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** idからアイテム情報取得 */
  getItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: never;
      };
    };
  };
  /** タイプ一覧取得 */
  getItemTypes: {
    responses: {
      /** @description 成功 */
      200: {
        content: never;
      };
    };
  };
}
