name: mobile / check

on:
  push:
    paths:
      - "mobile/**"
      - "common/**"
      - ".github/workflows/mobile-check.yml"

defaults:
  run:
    working-directory: ./mobile

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "1.9.2"
      - name: Run Biome
        run: biome ci .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./bun.lockb') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile
      - run: bun run typecheck

  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: latest
  #     - name: Cache node_modules
  #       id: cache-node-modules
  #       uses: actions/cache@v4
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('./bun.lockb') }}
  #     - name: Install dependencies
  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
  #       run: bun install --frozen-lockfile
  #     - run: bun run test:unit

  # db-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: latest
  #     - name: Cache node_modules
  #       id: cache-node-modules
  #       uses: actions/cache@v4
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('./bun.lockb') }}
  #     - name: Install dependencies
  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
  #       run: bun install --frozen-lockfile
  #     - run: bun run test:db
