name: pos

on:
  pull_request:
    paths:
      - 'services/pos/**'
      - 'modules/common/**'
      - '.github/workflows/common-ci.yml'

defaults:
  run:
    working-directory: services/pos

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/actions/setup-deps'
      - run: pnpm run typecheck
