name: status / check

on:
  push:
    paths:
      - "**"
      - "!mobile/**"
      - "!common/**"
      - "!pos/**"
      - ".github/workflows/status-check.yml"

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./bun.lockb') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile
      - run: bun tsc
